package api

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/labstack/echo/v4"

	"comma-personal-backend/internal/db"
	"comma-personal-backend/internal/share"
	"comma-personal-backend/internal/storage"
)

// Share link defaults and caps. These keep the link's blast radius bounded:
// an operator can explicitly ask for up to thirty days, but the default is
// three days so a forgotten link does not stay live indefinitely.
const (
	defaultShareExpiresHours = 72
	maxShareExpiresHours     = 720 // 30 days
)

// shareMediaFiles whitelists every file name the /v1/share/:token/... media
// endpoint is allowed to stream. Anything outside this set is rejected
// before the storage layer is consulted, so a malicious token cannot use
// path traversal or guess at arbitrary files. HLS .ts segments are matched
// separately (by suffix) because their names are generated by ffmpeg.
var shareMediaFiles = map[string]bool{
	"index.m3u8":   true,
	"qcamera.ts":   true,
	"fcamera.hevc": false, // not exposed -- raw camera uploads are private
	"ecamera.hevc": false,
	"dcamera.hevc": false,
	"rlog":         false,
	"rlog.bz2":     false,
	"rlog.zst":     false,
	"qlog":         false,
	"qlog.bz2":     false,
	"qlog.zst":     false,
}

// shareMediaCameraDirs whitelists the per-camera subdirectory names that
// the HLS transcoder writes under each segment folder. Requests routed to
// any other sub-path are rejected with 404 before the filesystem is
// touched.
var shareMediaCameraDirs = map[string]bool{
	"fcamera": true,
	"ecamera": true,
	"dcamera": true,
}

// ShareHandler issues and consumes public read-only share links for a
// single route. It depends on a secret-signed token scheme (see
// internal/share) and never exposes data for any route other than the one
// baked into the token. When the server has no SESSION_SECRET configured
// the handler still registers its routes but every endpoint returns 501
// so the feature is transparently disabled.
type ShareHandler struct {
	queries       *db.Queries
	storage       *storage.Storage
	sessionSecret []byte

	// now is overridable in tests to exercise the expiry path without sleeping.
	now func() time.Time
}

// NewShareHandler constructs a ShareHandler. queries and storage must be
// non-nil in production; sessionSecret may be empty, in which case every
// endpoint short-circuits to 501.
func NewShareHandler(queries *db.Queries, s *storage.Storage, sessionSecret string) *ShareHandler {
	return &ShareHandler{
		queries:       queries,
		storage:       s,
		sessionSecret: []byte(sessionSecret),
		now:           time.Now,
	}
}

// createShareRequest is the JSON body accepted by POST
// /v1/routes/:dongle_id/:route_name/share. ExpiresInHours is optional;
// zero/negative values fall back to defaultShareExpiresHours, and values
// above maxShareExpiresHours are clamped down to the cap rather than
// rejected so a sloppy caller still gets a link (the response carries the
// actual expiry).
type createShareRequest struct {
	ExpiresInHours int `json:"expires_in_hours"`
}

// createShareResponse is the JSON body returned on POST success. The URL
// is absolute so clients can display or copy it without extra work; the
// token alone is also included because some integrations (e.g. a bot
// posting into chat) prefer to stitch the URL themselves.
type createShareResponse struct {
	URL       string    `json:"url"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

// shareSegment mirrors the per-segment block returned by GET
// /v1/route/:dongle_id/:route_name, trimmed to the fields a public
// viewer cares about. We expose the upload flags so the client can pick a
// valid camera without probing the media endpoint.
type shareSegment struct {
	Number          int32 `json:"number"`
	FcameraUploaded bool  `json:"fcameraUploaded"`
	EcameraUploaded bool  `json:"ecameraUploaded"`
	DcameraUploaded bool  `json:"dcameraUploaded"`
	QcameraUploaded bool  `json:"qcameraUploaded"`
}

// shareRouteResponse is the JSON body returned by GET /v1/share/:token. It
// is deliberately a strict subset of the authenticated route-detail
// response: no device identifier, no rlog/qlog flags, no upload timing.
// The MediaBaseURL field is a relative path the client concatenates with
// the per-camera/segment path to build HLS playlist URLs. Keeping it
// relative means the frontend does not need to know the backend origin.
type shareRouteResponse struct {
	RouteName    string         `json:"routeName"`
	StartTime    *time.Time     `json:"startTime"`
	EndTime      *time.Time     `json:"endTime"`
	SegmentCount int64          `json:"segmentCount"`
	Segments     []shareSegment `json:"segments"`
	Geometry     [][2]float64   `json:"geometry"`
	ExpiresAt    time.Time      `json:"expiresAt"`
	MediaBaseURL string         `json:"mediaBaseUrl"`
}

// RegisterCreateRoute registers POST /:dongle_id/:route_name/share on the
// given group. The group MUST already have session authentication applied
// because only an operator should be able to mint share links.
func (h *ShareHandler) RegisterCreateRoute(g *echo.Group) {
	g.POST("/:dongle_id/:route_name/share", h.CreateShare)
}

// RegisterPublicRoutes wires up the unauthenticated endpoints: the route
// metadata endpoint and the media streaming endpoint. These are the only
// routes a holder of a valid token may hit; everything else requires a
// session cookie or device JWT.
func (h *ShareHandler) RegisterPublicRoutes(e *echo.Echo) {
	e.GET("/v1/share/:token", h.GetShare)
	e.GET("/v1/share/:token/segments/:segment_num/:file", h.GetShareMedia)
	e.GET("/v1/share/:token/segments/:segment_num/:camera/:file", h.GetShareCameraMedia)
}

// CreateShare handles POST /v1/routes/:dongle_id/:route_name/share. It
// requires an operator session (enforced at the middleware level); the
// dongle_id in the URL is authoritative -- we look the route up by the
// (dongle_id, route_name) pair rather than trusting a body field.
func (h *ShareHandler) CreateShare(c echo.Context) error {
	if len(h.sessionSecret) == 0 {
		return c.JSON(http.StatusNotImplemented, errorResponse{
			Error: "share links are disabled: SESSION_SECRET is not configured",
			Code:  http.StatusNotImplemented,
		})
	}

	dongleID := c.Param("dongle_id")
	routeName := c.Param("route_name")

	// An operator session is not restricted to a single dongle, but we
	// still run checkDongleAccess so a device JWT that somehow reached
	// this group is rejected when it targets a foreign dongle_id.
	if handled, err := checkDongleAccess(c, dongleID); handled {
		return err
	}

	var req createShareRequest
	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, errorResponse{
			Error: "failed to parse request body",
			Code:  http.StatusBadRequest,
		})
	}

	hours := req.ExpiresInHours
	if hours <= 0 {
		hours = defaultShareExpiresHours
	}
	if hours > maxShareExpiresHours {
		hours = maxShareExpiresHours
	}
	expiresAt := h.now().Add(time.Duration(hours) * time.Hour)

	ctx := c.Request().Context()
	route, err := h.queries.GetRoute(ctx, db.GetRouteParams{
		DongleID:  dongleID,
		RouteName: routeName,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return c.JSON(http.StatusNotFound, errorResponse{
				Error: fmt.Sprintf("route %s not found", routeName),
				Code:  http.StatusNotFound,
			})
		}
		return c.JSON(http.StatusInternalServerError, errorResponse{
			Error: "failed to retrieve route",
			Code:  http.StatusInternalServerError,
		})
	}

	token, err := share.Sign(h.sessionSecret, route.ID, expiresAt)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, errorResponse{
			Error: "failed to sign share token",
			Code:  http.StatusInternalServerError,
		})
	}

	url := buildShareURL(c.Request(), token)
	return c.JSON(http.StatusOK, createShareResponse{
		URL:       url,
		Token:     token,
		ExpiresAt: expiresAt,
	})
}

// GetShare handles GET /v1/share/:token. It verifies the token, loads the
// route and its segments + geometry, and returns a trimmed-down JSON
// payload that the public share page can render without needing any
// authenticated endpoints.
func (h *ShareHandler) GetShare(c echo.Context) error {
	routeID, expiresAt, handlerErr := h.consumeToken(c.Param("token"))
	if handlerErr != nil {
		return writeShareTokenError(c, handlerErr)
	}

	ctx := c.Request().Context()
	route, err := h.queries.GetRouteByID(ctx, routeID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// The token signed a route that has since been deleted. We
			// surface this as a plain 404 so the public viewer sees the
			// same response as any other not-found lookup.
			return c.JSON(http.StatusNotFound, errorResponse{
				Error: "route not found",
				Code:  http.StatusNotFound,
			})
		}
		return c.JSON(http.StatusInternalServerError, errorResponse{
			Error: "failed to retrieve route",
			Code:  http.StatusInternalServerError,
		})
	}

	segments, err := h.queries.ListSegmentsByRoute(ctx, route.ID)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, errorResponse{
			Error: "failed to retrieve segments",
			Code:  http.StatusInternalServerError,
		})
	}

	segResponses := make([]shareSegment, 0, len(segments))
	for _, s := range segments {
		segResponses = append(segResponses, shareSegment{
			Number:          s.SegmentNumber,
			FcameraUploaded: s.FcameraUploaded,
			EcameraUploaded: s.EcameraUploaded,
			DcameraUploaded: s.DcameraUploaded,
			QcameraUploaded: s.QcameraUploaded,
		})
	}

	// Geometry is optional: a route with no location points still gets a
	// valid share link with an empty geometry array.
	geom := h.lookupGeometry(ctx, route.DongleID, route.RouteName)

	var startTime, endTime *time.Time
	if route.StartTime.Valid {
		startTime = &route.StartTime.Time
	}
	if route.EndTime.Valid {
		endTime = &route.EndTime.Time
	}

	return c.JSON(http.StatusOK, shareRouteResponse{
		RouteName:    route.RouteName,
		StartTime:    startTime,
		EndTime:      endTime,
		SegmentCount: int64(len(segments)),
		Segments:     segResponses,
		Geometry:     geom,
		ExpiresAt:    expiresAt,
		MediaBaseURL: fmt.Sprintf("/v1/share/%s/segments", c.Param("token")),
	})
}

// GetShareMedia handles GET /v1/share/:token/segments/:segment_num/:file.
// It streams the requested file from disk after verifying the token scopes
// to the right route. Used for top-level segment artifacts such as the
// qcamera.ts preview.
func (h *ShareHandler) GetShareMedia(c echo.Context) error {
	routeID, _, handlerErr := h.consumeToken(c.Param("token"))
	if handlerErr != nil {
		return writeShareTokenError(c, handlerErr)
	}

	segNum, ok := parseSegmentNumber(c.Param("segment_num"))
	if !ok {
		return c.JSON(http.StatusBadRequest, errorResponse{
			Error: "invalid segment_num",
			Code:  http.StatusBadRequest,
		})
	}

	file := c.Param("file")
	if !isAllowedShareMediaFile(file) {
		return c.JSON(http.StatusNotFound, errorResponse{
			Error: "file not found",
			Code:  http.StatusNotFound,
		})
	}

	route, routeErr := h.routeByID(c.Request().Context(), routeID)
	if routeErr != nil {
		return writeShareTokenError(c, routeErr)
	}

	path := h.storage.Path(route.DongleID, route.RouteName, strconv.Itoa(segNum), file)
	return serveShareFile(c, path, file)
}

// GetShareCameraMedia handles GET
// /v1/share/:token/segments/:segment_num/:camera/:file. It targets the HLS
// output under the per-camera sub-directory; the :file parameter is the
// playlist or a .ts chunk.
func (h *ShareHandler) GetShareCameraMedia(c echo.Context) error {
	routeID, _, handlerErr := h.consumeToken(c.Param("token"))
	if handlerErr != nil {
		return writeShareTokenError(c, handlerErr)
	}

	segNum, ok := parseSegmentNumber(c.Param("segment_num"))
	if !ok {
		return c.JSON(http.StatusBadRequest, errorResponse{
			Error: "invalid segment_num",
			Code:  http.StatusBadRequest,
		})
	}

	camera := c.Param("camera")
	if !shareMediaCameraDirs[camera] {
		return c.JSON(http.StatusNotFound, errorResponse{
			Error: "file not found",
			Code:  http.StatusNotFound,
		})
	}

	file := c.Param("file")
	if !isAllowedHLSFile(file) {
		return c.JSON(http.StatusNotFound, errorResponse{
			Error: "file not found",
			Code:  http.StatusNotFound,
		})
	}

	route, routeErr := h.routeByID(c.Request().Context(), routeID)
	if routeErr != nil {
		return writeShareTokenError(c, routeErr)
	}

	segDir := h.storage.Path(route.DongleID, route.RouteName, strconv.Itoa(segNum), "")
	path := filepath.Join(segDir, camera, file)
	return serveShareFile(c, path, file)
}

// shareStatusError is a typed error used by the internal helpers to signal
// the HTTP status and message a handler should return. Using a dedicated
// type lets us keep a single writeShareTokenError funnel that always emits
// the project's canonical {"error", "code"} envelope rather than Echo's
// built-in {"message": ...} shape.
type shareStatusError struct {
	status  int
	message string
}

func (e *shareStatusError) Error() string { return e.message }

// writeShareTokenError renders a shareStatusError into the standard JSON
// envelope with the appropriate status code. Any other error type is
// coerced to 500 Internal Server Error with a generic message because the
// callers should never reach it with a bare error.
func writeShareTokenError(c echo.Context, err error) error {
	var se *shareStatusError
	if errors.As(err, &se) {
		return c.JSON(se.status, errorResponse{
			Error: se.message,
			Code:  se.status,
		})
	}
	return c.JSON(http.StatusInternalServerError, errorResponse{
		Error: "internal server error",
		Code:  http.StatusInternalServerError,
	})
}

// consumeToken validates the token string and returns the embedded route
// ID along with the token's expiry time. It maps the share.Parse error
// taxonomy onto the expected HTTP responses: expired tokens produce 410
// Gone, anything else (tamper, wrong secret, malformed) collapses to 401,
// and a missing session secret produces 501 Not Implemented.
func (h *ShareHandler) consumeToken(token string) (int32, time.Time, error) {
	if len(h.sessionSecret) == 0 {
		return 0, time.Time{}, &shareStatusError{
			status:  http.StatusNotImplemented,
			message: "share links are disabled: SESSION_SECRET is not configured",
		}
	}
	routeID, exp, err := share.ParseFull(h.sessionSecret, token, h.now())
	if err != nil {
		switch {
		case errors.Is(err, share.ErrExpired):
			return 0, time.Time{}, &shareStatusError{
				status:  http.StatusGone,
				message: "share link has expired",
			}
		default:
			return 0, time.Time{}, &shareStatusError{
				status:  http.StatusUnauthorized,
				message: "invalid share token",
			}
		}
	}
	return routeID, exp, nil
}

// routeByID looks up a route from its primary key and converts pgx.ErrNoRows
// into a 404 shareStatusError so the share handlers don't have to repeat
// the same error mapping in each route that needs to resolve a token to a
// (dongle_id, route_name) pair.
func (h *ShareHandler) routeByID(ctx context.Context, routeID int32) (db.Route, error) {
	route, err := h.queries.GetRouteByID(ctx, routeID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return db.Route{}, &shareStatusError{
				status:  http.StatusNotFound,
				message: "route not found",
			}
		}
		return db.Route{}, &shareStatusError{
			status:  http.StatusInternalServerError,
			message: "failed to retrieve route",
		}
	}
	return route, nil
}

// lookupGeometry fetches the route's GPS track as a slice of [lat, lng]
// pairs. A missing or malformed geometry yields an empty slice rather
// than an error; the share view is still useful even if the map is empty.
func (h *ShareHandler) lookupGeometry(ctx context.Context, dongleID, routeName string) [][2]float64 {
	wkt, err := h.queries.GetRouteGeometryWKT(ctx, db.GetRouteGeometryWKTParams{
		DongleID:  dongleID,
		RouteName: routeName,
	})
	if err != nil {
		return nil
	}
	if !wkt.Valid || strings.TrimSpace(wkt.String) == "" {
		return nil
	}
	points, err := parseLineStringWKT(wkt.String)
	if err != nil {
		return nil
	}
	out := make([][2]float64, 0, len(points))
	for _, p := range points {
		out = append(out, [2]float64{p.Lat, p.Lon})
	}
	return out
}

// parseSegmentNumber parses a segment-number path parameter. It rejects
// anything that isn't a small non-negative integer so a malformed URL
// can't reach os.Open.
func parseSegmentNumber(s string) (int, bool) {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0, false
	}
	if n < 0 || n > 9999 {
		return 0, false
	}
	return n, true
}

// isAllowedShareMediaFile returns true for files that the public share
// endpoint is allowed to serve. Files explicitly listed as "false" in
// shareMediaFiles are blocked; anything outside the map is also blocked
// so the default is deny.
func isAllowedShareMediaFile(name string) bool {
	allowed, ok := shareMediaFiles[name]
	if !ok {
		return false
	}
	return allowed
}

// isAllowedHLSFile accepts the HLS index playlist and any segment .ts file.
// The name must not contain directory separators or parent-directory
// references; validate both before touching the filesystem.
func isAllowedHLSFile(name string) bool {
	if name == "" || strings.ContainsAny(name, "/\\") {
		return false
	}
	if name == ".." || strings.Contains(name, "..") {
		return false
	}
	if name == "index.m3u8" {
		return true
	}
	if strings.HasSuffix(name, ".ts") {
		return true
	}
	return false
}

// serveShareFile streams a file from disk with the appropriate Content-Type
// for the known HLS artefacts. It is the single path where the filesystem
// is touched by a share request, so it centralizes the missing-file and
// unreadable-file handling.
func serveShareFile(c echo.Context, path, file string) error {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return c.JSON(http.StatusNotFound, errorResponse{
				Error: "file not found",
				Code:  http.StatusNotFound,
			})
		}
		return c.JSON(http.StatusInternalServerError, errorResponse{
			Error: "failed to stat file",
			Code:  http.StatusInternalServerError,
		})
	}
	if info.IsDir() {
		return c.JSON(http.StatusNotFound, errorResponse{
			Error: "file not found",
			Code:  http.StatusNotFound,
		})
	}

	c.Response().Header().Set(echo.HeaderContentType, shareContentType(file))
	// Short cache TTL so a revoked route (or deleted file) stops being
	// served reasonably quickly. HLS players aggressively re-fetch the
	// playlist anyway, so a longer TTL is not especially helpful here.
	c.Response().Header().Set(echo.HeaderCacheControl, "public, max-age=60")
	return c.File(path)
}

// shareContentType picks a sensible MIME type for the known HLS + MPEG-TS
// file extensions. Falling back to application/octet-stream keeps us from
// mislabelling unexpected content.
func shareContentType(file string) string {
	switch {
	case strings.HasSuffix(file, ".m3u8"):
		return "application/vnd.apple.mpegurl"
	case strings.HasSuffix(file, ".ts"):
		return "video/mp2t"
	default:
		return "application/octet-stream"
	}
}

// buildShareURL constructs an absolute URL pointing at the /share/:token
// public page. It honours X-Forwarded-Proto / Host so deployments behind a
// reverse proxy get the right origin.
func buildShareURL(r *http.Request, token string) string {
	scheme := "http"
	if r.TLS != nil || strings.EqualFold(r.Header.Get("X-Forwarded-Proto"), "https") {
		scheme = "https"
	}
	host := r.Host
	if xfh := r.Header.Get("X-Forwarded-Host"); xfh != "" {
		host = xfh
	}
	if host == "" {
		host = "localhost"
	}
	return fmt.Sprintf("%s://%s/share/%s", scheme, host, token)
}
