// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_watchlist.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackWatchlist = `-- name: AckWatchlist :execrows
UPDATE plate_watchlist
SET acked_at   = $2,
    updated_at = now()
WHERE plate_hash = $1
`

type AckWatchlistParams struct {
	PlateHash []byte             `json:"plateHash"`
	AckedAt   pgtype.Timestamptz `json:"ackedAt"`
}

// Mark a plate's watchlist row as acknowledged at the given time. The
// alert feed treats acked rows as "seen", de-emphasizing them in the UI
// without removing them. Returns rows-affected so the caller can detect
// "no such plate".
func (q *Queries) AckWatchlist(ctx context.Context, arg AckWatchlistParams) (int64, error) {
	result, err := q.db.Exec(ctx, ackWatchlist, arg.PlateHash, arg.AckedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countUnackedAlerts = `-- name: CountUnackedAlerts :one
SELECT COUNT(*)::BIGINT
FROM plate_watchlist
WHERE kind = 'alerted'
  AND acked_at IS NULL
`

// Used by the dashboard alert badge ("3 unacked alerts").
func (q *Queries) CountUnackedAlerts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnackedAlerts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getWatchlistByHash = `-- name: GetWatchlistByHash :one
SELECT id, plate_hash, label_ciphertext, kind, severity,
       first_alert_at, last_alert_at, acked_at, notes,
       created_at, updated_at
FROM plate_watchlist
WHERE plate_hash = $1
`

type GetWatchlistByHashRow struct {
	ID              int64              `json:"id"`
	PlateHash       []byte             `json:"plateHash"`
	LabelCiphertext []byte             `json:"labelCiphertext"`
	Kind            string             `json:"kind"`
	Severity        pgtype.Int2        `json:"severity"`
	FirstAlertAt    pgtype.Timestamptz `json:"firstAlertAt"`
	LastAlertAt     pgtype.Timestamptz `json:"lastAlertAt"`
	AckedAt         pgtype.Timestamptz `json:"ackedAt"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// Look up a plate's current watchlist row, or pgx.ErrNoRows when none
// exists. Used by the alert-evaluation worker to decide whether the
// plate is whitelisted (suppress) before computing severity.
func (q *Queries) GetWatchlistByHash(ctx context.Context, plateHash []byte) (GetWatchlistByHashRow, error) {
	row := q.db.QueryRow(ctx, getWatchlistByHash, plateHash)
	var i GetWatchlistByHashRow
	err := row.Scan(
		&i.ID,
		&i.PlateHash,
		&i.LabelCiphertext,
		&i.Kind,
		&i.Severity,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.AckedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, plate_hash, label_ciphertext, kind, severity,
       first_alert_at, last_alert_at, acked_at, notes,
       created_at, updated_at
FROM plate_watchlist
WHERE kind = 'alerted'
  AND ($3::boolean IS NULL
       OR ($3::boolean = TRUE  AND acked_at IS NOT NULL)
       OR ($3::boolean = FALSE AND acked_at IS NULL))
ORDER BY last_alert_at DESC NULLS LAST, id DESC
LIMIT $1 OFFSET $2
`

type ListAlertsParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	AckedFilter pgtype.Bool `json:"ackedFilter"`
}

type ListAlertsRow struct {
	ID              int64              `json:"id"`
	PlateHash       []byte             `json:"plateHash"`
	LabelCiphertext []byte             `json:"labelCiphertext"`
	Kind            string             `json:"kind"`
	Severity        pgtype.Int2        `json:"severity"`
	FirstAlertAt    pgtype.Timestamptz `json:"firstAlertAt"`
	LastAlertAt     pgtype.Timestamptz `json:"lastAlertAt"`
	AckedAt         pgtype.Timestamptz `json:"ackedAt"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// The alert feed: alerted-kind rows ordered by recency of last_alert_at,
// with optional filtering on whether the row is currently acknowledged.
// Pass NULL for @acked_filter to include both states. Pagination via
// limit/offset to match the events feed style elsewhere in the project.
func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.Limit, arg.Offset, arg.AckedFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsRow
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.PlateHash,
			&i.LabelCiphertext,
			&i.Kind,
			&i.Severity,
			&i.FirstAlertAt,
			&i.LastAlertAt,
			&i.AckedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchlistByKind = `-- name: ListWatchlistByKind :many
SELECT id, plate_hash, label_ciphertext, kind, severity,
       first_alert_at, last_alert_at, acked_at, notes,
       created_at, updated_at
FROM plate_watchlist
WHERE kind = $1
ORDER BY updated_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListWatchlistByKindParams struct {
	Kind   string `json:"kind"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListWatchlistByKindRow struct {
	ID              int64              `json:"id"`
	PlateHash       []byte             `json:"plateHash"`
	LabelCiphertext []byte             `json:"labelCiphertext"`
	Kind            string             `json:"kind"`
	Severity        pgtype.Int2        `json:"severity"`
	FirstAlertAt    pgtype.Timestamptz `json:"firstAlertAt"`
	LastAlertAt     pgtype.Timestamptz `json:"lastAlertAt"`
	AckedAt         pgtype.Timestamptz `json:"ackedAt"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// Paginated list of watchlist rows of a given kind, newest update first.
// Used by the watchlist UI tabs (alerted / whitelist / note).
func (q *Queries) ListWatchlistByKind(ctx context.Context, arg ListWatchlistByKindParams) ([]ListWatchlistByKindRow, error) {
	rows, err := q.db.Query(ctx, listWatchlistByKind, arg.Kind, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWatchlistByKindRow
	for rows.Next() {
		var i ListWatchlistByKindRow
		if err := rows.Scan(
			&i.ID,
			&i.PlateHash,
			&i.LabelCiphertext,
			&i.Kind,
			&i.Severity,
			&i.FirstAlertAt,
			&i.LastAlertAt,
			&i.AckedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxOpenSeverity = `-- name: MaxOpenSeverity :one
SELECT COALESCE(MAX(severity), 0)::SMALLINT
FROM plate_watchlist
WHERE kind = 'alerted'
  AND acked_at IS NULL
`

// Highest severity among unacknowledged alerts, or 0 if none. Drives the
// color of the dashboard alert badge. COALESCE so the query always
// returns a row instead of NULL when there are no open alerts.
func (q *Queries) MaxOpenSeverity(ctx context.Context) (int16, error) {
	row := q.db.QueryRow(ctx, maxOpenSeverity)
	var column_1 int16
	err := row.Scan(&column_1)
	return column_1, err
}

const removeWatchlist = `-- name: RemoveWatchlist :execrows
DELETE FROM plate_watchlist
WHERE plate_hash = $1
`

// Delete the watchlist row for a plate. Returns rows-affected so the
// caller can distinguish "deleted" from "wasn't there to begin with".
func (q *Queries) RemoveWatchlist(ctx context.Context, plateHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, removeWatchlist, plateHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unackWatchlist = `-- name: UnackWatchlist :execrows
UPDATE plate_watchlist
SET acked_at   = NULL,
    updated_at = now()
WHERE plate_hash = $1
`

// Reverse of AckWatchlist: clear acked_at so the alert resurfaces.
func (q *Queries) UnackWatchlist(ctx context.Context, plateHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, unackWatchlist, plateHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWatchlistAlerted = `-- name: UpsertWatchlistAlerted :one
INSERT INTO plate_watchlist (
    plate_hash,
    label_ciphertext,
    kind,
    severity,
    first_alert_at,
    last_alert_at,
    notes
)
VALUES ($1, $2, 'alerted', $3, $5, $5, $4)
ON CONFLICT (plate_hash) DO UPDATE
SET kind             = 'alerted',
    severity         = EXCLUDED.severity,
    label_ciphertext = COALESCE(EXCLUDED.label_ciphertext,
                                plate_watchlist.label_ciphertext),
    -- first_alert_at sticks: an existing alerted plate keeps its initial
    -- alert timestamp even on subsequent re-fires.
    first_alert_at   = COALESCE(plate_watchlist.first_alert_at,
                                EXCLUDED.first_alert_at),
    last_alert_at    = EXCLUDED.last_alert_at,
    -- New alert event clears any prior ack so the operator sees it again.
    acked_at         = NULL,
    notes            = COALESCE(EXCLUDED.notes, plate_watchlist.notes),
    updated_at       = now()
RETURNING id, plate_hash, label_ciphertext, kind, severity,
          first_alert_at, last_alert_at, acked_at, notes,
          created_at, updated_at
`

type UpsertWatchlistAlertedParams struct {
	PlateHash       []byte             `json:"plateHash"`
	LabelCiphertext []byte             `json:"labelCiphertext"`
	Severity        pgtype.Int2        `json:"severity"`
	Notes           pgtype.Text        `json:"notes"`
	AlertAt         pgtype.Timestamptz `json:"alertAt"`
}

type UpsertWatchlistAlertedRow struct {
	ID              int64              `json:"id"`
	PlateHash       []byte             `json:"plateHash"`
	LabelCiphertext []byte             `json:"labelCiphertext"`
	Kind            string             `json:"kind"`
	Severity        pgtype.Int2        `json:"severity"`
	FirstAlertAt    pgtype.Timestamptz `json:"firstAlertAt"`
	LastAlertAt     pgtype.Timestamptz `json:"lastAlertAt"`
	AckedAt         pgtype.Timestamptz `json:"ackedAt"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// Insert a new alerted-kind row for a plate, or refresh an existing one
// so its severity/last_alert_at advance and acked_at clears. The
// transition from whitelist or note into alerted is intentionally
// permitted: the heuristic decided the plate is alert-worthy regardless
// of the previous state. Operators reverse it via UpsertWatchlistWhitelist
// or RemoveWatchlist.
func (q *Queries) UpsertWatchlistAlerted(ctx context.Context, arg UpsertWatchlistAlertedParams) (UpsertWatchlistAlertedRow, error) {
	row := q.db.QueryRow(ctx, upsertWatchlistAlerted,
		arg.PlateHash,
		arg.LabelCiphertext,
		arg.Severity,
		arg.Notes,
		arg.AlertAt,
	)
	var i UpsertWatchlistAlertedRow
	err := row.Scan(
		&i.ID,
		&i.PlateHash,
		&i.LabelCiphertext,
		&i.Kind,
		&i.Severity,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.AckedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWatchlistWhitelist = `-- name: UpsertWatchlistWhitelist :one
INSERT INTO plate_watchlist (
    plate_hash,
    label_ciphertext,
    kind,
    notes
)
VALUES ($1, $2, 'whitelist', $3)
ON CONFLICT (plate_hash) DO UPDATE
SET kind             = 'whitelist',
    label_ciphertext = COALESCE(EXCLUDED.label_ciphertext,
                                plate_watchlist.label_ciphertext),
    -- Clearing severity and the alert timestamps prevents stale alert
    -- entries from lingering once the operator has whitelisted.
    severity         = NULL,
    first_alert_at   = NULL,
    last_alert_at    = NULL,
    acked_at         = NULL,
    notes            = COALESCE(EXCLUDED.notes, plate_watchlist.notes),
    updated_at       = now()
RETURNING id, plate_hash, label_ciphertext, kind, severity,
          first_alert_at, last_alert_at, acked_at, notes,
          created_at, updated_at
`

type UpsertWatchlistWhitelistParams struct {
	PlateHash       []byte      `json:"plateHash"`
	LabelCiphertext []byte      `json:"labelCiphertext"`
	Notes           pgtype.Text `json:"notes"`
}

type UpsertWatchlistWhitelistRow struct {
	ID              int64              `json:"id"`
	PlateHash       []byte             `json:"plateHash"`
	LabelCiphertext []byte             `json:"labelCiphertext"`
	Kind            string             `json:"kind"`
	Severity        pgtype.Int2        `json:"severity"`
	FirstAlertAt    pgtype.Timestamptz `json:"firstAlertAt"`
	LastAlertAt     pgtype.Timestamptz `json:"lastAlertAt"`
	AckedAt         pgtype.Timestamptz `json:"ackedAt"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

// Insert a new whitelist row for a plate, or update an existing row to
// the whitelist kind. Whitelisting an alerted plate is the operator's
// "this is fine, stop alerting on it" action: the alert timestamps and
// severity are cleared so the alert feed no longer surfaces the row.
func (q *Queries) UpsertWatchlistWhitelist(ctx context.Context, arg UpsertWatchlistWhitelistParams) (UpsertWatchlistWhitelistRow, error) {
	row := q.db.QueryRow(ctx, upsertWatchlistWhitelist, arg.PlateHash, arg.LabelCiphertext, arg.Notes)
	var i UpsertWatchlistWhitelistRow
	err := row.Scan(
		&i.ID,
		&i.PlateHash,
		&i.LabelCiphertext,
		&i.Kind,
		&i.Severity,
		&i.FirstAlertAt,
		&i.LastAlertAt,
		&i.AckedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
