// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_encounters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateEncountersPlateHash = `-- name: BulkUpdateEncountersPlateHash :execrows
UPDATE plate_encounters
SET plate_hash = $1
WHERE plate_hash = $2
`

type BulkUpdateEncountersPlateHashParams struct {
	NewPlateHash []byte `json:"newPlateHash"`
	OldPlateHash []byte `json:"oldPlateHash"`
}

// Plate-merge path on the encounters table: rewrite plate_hash on every
// encounter that currently points at the source hash. After the matching
// detection-side update runs, the encounters' hash is rewritten so the
// per-route review UI reflects the merged identity even before the
// aggregator re-runs. The merge handler immediately re-triggers
// aggregation on every affected route, which will DELETE+UPSERT
// encounters cleanly; this UPDATE is the interim coherent-state pass.
//
// The unique index on (dongle_id, route, plate_hash, first_seen_ts) can
// in principle be violated if two encounters share the same first_seen_ts
// after a merge. In practice that requires both encounters to start on
// the exact same wall-clock instant in the same route, which is
// vanishingly unlikely; if it ever fires the transaction rolls back and
// the operator surfaces a 500, which is the right failure mode for a
// rare data race.
func (q *Queries) BulkUpdateEncountersPlateHash(ctx context.Context, arg BulkUpdateEncountersPlateHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkUpdateEncountersPlateHash, arg.NewPlateHash, arg.OldPlateHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEncountersForPlate = `-- name: CountEncountersForPlate :one
SELECT COUNT(*)::BIGINT
FROM plate_encounters
WHERE plate_hash = $1
`

// Number of encounter rows for a plate, used by the alert listing to
// render an "encounter_count" badge without paging through the full
// list. BIGINT so the count never overflows on a heavy producer.
func (q *Queries) CountEncountersForPlate(ctx context.Context, plateHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, countEncountersForPlate, plateHash)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteEncountersForRoute = `-- name: DeleteEncountersForRoute :execrows
DELETE FROM plate_encounters
WHERE dongle_id = $1 AND route = $2
`

type DeleteEncountersForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

// Wipe the encounter rows for one route. The aggregator calls this
// before re-running over a route so the new pass starts from a clean
// slate. Returns the number of rows deleted so the caller can log how
// much state it discarded.
func (q *Queries) DeleteEncountersForRoute(ctx context.Context, arg DeleteEncountersForRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEncountersForRoute, arg.DongleID, arg.Route)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanedEncounters = `-- name: DeleteOrphanedEncounters :execrows
DELETE FROM plate_encounters pe
WHERE NOT EXISTS (
        SELECT 1
        FROM plate_detections d
        WHERE d.dongle_id  = pe.dongle_id
          AND d.route      = pe.route
          AND d.plate_hash = pe.plate_hash
          AND d.frame_ts BETWEEN pe.first_seen_ts AND pe.last_seen_ts
  )
`

// Retention sweep: drop encounter rows whose underlying detections have
// already been pruned. After the per-detection retention pass runs, an
// encounter whose entire (first_seen_ts, last_seen_ts) window has been
// emptied of detections has no evidence left and should be cleaned up
// to keep the per-route review UI from showing zombie rows.
//
// Match semantics: an encounter survives if ANY detection still exists
// with the same (dongle_id, route, plate_hash) AND a frame_ts inside
// the encounter's [first_seen_ts, last_seen_ts] window. The plate_hash
// column scopes the join so an encounter for plate A is not kept alive
// by detections of plate B that happen to overlap in time.
// Returns the number of orphan encounter rows deleted.
func (q *Queries) DeleteOrphanedEncounters(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanedEncounters)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const distinctRoutesForEncountersPlateHash = `-- name: DistinctRoutesForEncountersPlateHash :many
SELECT DISTINCT dongle_id, route
FROM plate_encounters
WHERE plate_hash = $1
ORDER BY dongle_id ASC, route ASC
`

type DistinctRoutesForEncountersPlateHashRow struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

// All (dongle_id, route) pairs that have at least one encounter for the
// given plate_hash. Companion to DistinctRoutesForPlateHash on the
// detections side; the merge handler unions the two so a route whose
// detections were retention-pruned but whose encounter survives is still
// re-aggregated. Ordered for deterministic enqueue order.
func (q *Queries) DistinctRoutesForEncountersPlateHash(ctx context.Context, plateHash []byte) ([]DistinctRoutesForEncountersPlateHashRow, error) {
	rows, err := q.db.Query(ctx, distinctRoutesForEncountersPlateHash, plateHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DistinctRoutesForEncountersPlateHashRow
	for rows.Next() {
		var i DistinctRoutesForEncountersPlateHashRow
		if err := rows.Scan(&i.DongleID, &i.Route); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostRecentEncounterForPlate = `-- name: GetMostRecentEncounterForPlate :one
SELECT id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
       detection_count, turn_count, max_internal_gap_seconds,
       status, bbox_first, bbox_last,
       created_at, updated_at
FROM plate_encounters
WHERE plate_hash = $1
ORDER BY last_seen_ts DESC NULLS LAST, id DESC
LIMIT 1
`

type GetMostRecentEncounterForPlateRow struct {
	ID                    int64              `json:"id"`
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

// The single most-recently-finished encounter for a plate. Used by the
// alert/whitelist listing endpoints to populate the latest_route panel
// (which device, which route, when) without loading the full encounter
// history. pgx.ErrNoRows when the plate has never been seen.
func (q *Queries) GetMostRecentEncounterForPlate(ctx context.Context, plateHash []byte) (GetMostRecentEncounterForPlateRow, error) {
	row := q.db.QueryRow(ctx, getMostRecentEncounterForPlate, plateHash)
	var i GetMostRecentEncounterForPlateRow
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.Route,
		&i.PlateHash,
		&i.FirstSeenTs,
		&i.LastSeenTs,
		&i.DetectionCount,
		&i.TurnCount,
		&i.MaxInternalGapSeconds,
		&i.Status,
		&i.BboxFirst,
		&i.BboxLast,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctPlatesEncounteredInWindow = `-- name: ListDistinctPlatesEncounteredInWindow :many
SELECT DISTINCT dongle_id, plate_hash
FROM plate_encounters
WHERE last_seen_ts  >= $1
  AND first_seen_ts <= $2
ORDER BY dongle_id ASC, plate_hash ASC
`

type ListDistinctPlatesEncounteredInWindowParams struct {
	WindowStart pgtype.Timestamptz `json:"windowStart"`
	WindowEnd   pgtype.Timestamptz `json:"windowEnd"`
}

type ListDistinctPlatesEncounteredInWindowRow struct {
	DongleID  string `json:"dongleId"`
	PlateHash []byte `json:"plateHash"`
}

// All distinct (dongle_id, plate_hash) pairs that have at least one
// encounter overlapping the supplied [window_start, window_end]
// range. Used by the heuristic re-evaluation endpoint
// (POST /v1/alpr/heuristic/reevaluate) to enumerate which plates need
// to be re-scored against fresh tuning thresholds without scanning the
// entire encounter table. The window is inclusive on both ends and
// matches the same overlap semantics as ListEncountersForPlateInWindow.
// Ordered for deterministic test fixtures.
func (q *Queries) ListDistinctPlatesEncounteredInWindow(ctx context.Context, arg ListDistinctPlatesEncounteredInWindowParams) ([]ListDistinctPlatesEncounteredInWindowRow, error) {
	rows, err := q.db.Query(ctx, listDistinctPlatesEncounteredInWindow, arg.WindowStart, arg.WindowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctPlatesEncounteredInWindowRow
	for rows.Next() {
		var i ListDistinctPlatesEncounteredInWindowRow
		if err := rows.Scan(&i.DongleID, &i.PlateHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForPlate = `-- name: ListEncountersForPlate :many
SELECT id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
       detection_count, turn_count, max_internal_gap_seconds,
       status, bbox_first, bbox_last,
       created_at, updated_at
FROM plate_encounters
WHERE plate_hash = $1
ORDER BY last_seen_ts DESC, id DESC
`

type ListEncountersForPlateRow struct {
	ID                    int64              `json:"id"`
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

// All encounters of a single plate across every route, newest first.
// Backs the plate-detail page and feeds the stalking heuristic's
// "recurring plate" lookups.
func (q *Queries) ListEncountersForPlate(ctx context.Context, plateHash []byte) ([]ListEncountersForPlateRow, error) {
	rows, err := q.db.Query(ctx, listEncountersForPlate, plateHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncountersForPlateRow
	for rows.Next() {
		var i ListEncountersForPlateRow
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForPlateInWindow = `-- name: ListEncountersForPlateInWindow :many
SELECT id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
       detection_count, turn_count, max_internal_gap_seconds,
       status, bbox_first, bbox_last,
       created_at, updated_at
FROM plate_encounters
WHERE plate_hash    = $1
  AND last_seen_ts >= $2
  AND first_seen_ts <= $3
ORDER BY last_seen_ts DESC, id DESC
`

type ListEncountersForPlateInWindowParams struct {
	PlateHash   []byte             `json:"plateHash"`
	LastSeenTs  pgtype.Timestamptz `json:"lastSeenTs"`
	FirstSeenTs pgtype.Timestamptz `json:"firstSeenTs"`
}

type ListEncountersForPlateInWindowRow struct {
	ID                    int64              `json:"id"`
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

// Encounters for a plate that overlap a given time window. The window is
// inclusive on both ends. Used by the stalking heuristic to count how
// many recent times the suspect plate was seen, without paging through
// the entire history.
func (q *Queries) ListEncountersForPlateInWindow(ctx context.Context, arg ListEncountersForPlateInWindowParams) ([]ListEncountersForPlateInWindowRow, error) {
	rows, err := q.db.Query(ctx, listEncountersForPlateInWindow, arg.PlateHash, arg.LastSeenTs, arg.FirstSeenTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncountersForPlateInWindowRow
	for rows.Next() {
		var i ListEncountersForPlateInWindowRow
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForPlateInWindowWithStartGPS = `-- name: ListEncountersForPlateInWindowWithStartGPS :many
SELECT pe.id, pe.dongle_id, pe.route, pe.plate_hash,
       pe.first_seen_ts, pe.last_seen_ts,
       pe.detection_count, pe.turn_count, pe.max_internal_gap_seconds,
       pe.status, pe.bbox_first, pe.bbox_last,
       pe.created_at, pe.updated_at,
       pd.gps_lat AS start_lat,
       pd.gps_lng AS start_lng
FROM plate_encounters pe
LEFT JOIN LATERAL (
    SELECT gps_lat, gps_lng
    FROM plate_detections d
    WHERE d.dongle_id  = pe.dongle_id
      AND d.route      = pe.route
      AND d.plate_hash = pe.plate_hash
      AND d.frame_ts   = pe.first_seen_ts
    LIMIT 1
) pd ON TRUE
WHERE pe.plate_hash    = $1
  AND pe.last_seen_ts >= $2
  AND pe.first_seen_ts <= $3
ORDER BY pe.last_seen_ts DESC, pe.id DESC
`

type ListEncountersForPlateInWindowWithStartGPSParams struct {
	PlateHash   []byte             `json:"plateHash"`
	LastSeenTs  pgtype.Timestamptz `json:"lastSeenTs"`
	FirstSeenTs pgtype.Timestamptz `json:"firstSeenTs"`
}

type ListEncountersForPlateInWindowWithStartGPSRow struct {
	ID                    int64              `json:"id"`
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
	StartLat              pgtype.Float8      `json:"startLat"`
	StartLng              pgtype.Float8      `json:"startLng"`
}

// Same window scan as ListEncountersForPlateInWindow but joined with the
// plate's first-detection GPS for that encounter. The stalking heuristic
// needs the start coordinates of each encounter to bucket them into geo
// cells (cross_route_geo_spread); without the join it would have to
// issue one detection lookup per encounter.
//
// LEFT JOIN: an encounter without a matching detection at first_seen_ts
// (extremely rare, but possible after a manual correction or partial
// delete) still appears with NULL gps fields; the heuristic treats those
// as "no GPS" rather than dropping the encounter.
func (q *Queries) ListEncountersForPlateInWindowWithStartGPS(ctx context.Context, arg ListEncountersForPlateInWindowWithStartGPSParams) ([]ListEncountersForPlateInWindowWithStartGPSRow, error) {
	rows, err := q.db.Query(ctx, listEncountersForPlateInWindowWithStartGPS, arg.PlateHash, arg.LastSeenTs, arg.FirstSeenTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncountersForPlateInWindowWithStartGPSRow
	for rows.Next() {
		var i ListEncountersForPlateInWindowWithStartGPSRow
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartLat,
			&i.StartLng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForRoute = `-- name: ListEncountersForRoute :many
SELECT id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
       detection_count, turn_count, max_internal_gap_seconds,
       status, bbox_first, bbox_last,
       created_at, updated_at
FROM plate_encounters
WHERE dongle_id = $1 AND route = $2
ORDER BY first_seen_ts ASC, id ASC
`

type ListEncountersForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

type ListEncountersForRouteRow struct {
	ID                    int64              `json:"id"`
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

// All encounter rows for a route, ordered by first_seen_ts. Powers the
// per-route review UI ("which plates did we see on this drive").
func (q *Queries) ListEncountersForRoute(ctx context.Context, arg ListEncountersForRouteParams) ([]ListEncountersForRouteRow, error) {
	rows, err := q.db.Query(ctx, listEncountersForRoute, arg.DongleID, arg.Route)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncountersForRouteRow
	for rows.Next() {
		var i ListEncountersForRouteRow
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEncounter = `-- name: UpsertEncounter :one
INSERT INTO plate_encounters (
    dongle_id,
    route,
    plate_hash,
    first_seen_ts,
    last_seen_ts,
    detection_count,
    turn_count,
    max_internal_gap_seconds,
    status,
    bbox_first,
    bbox_last
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (dongle_id, route, plate_hash, first_seen_ts) DO UPDATE
SET last_seen_ts             = EXCLUDED.last_seen_ts,
    detection_count          = EXCLUDED.detection_count,
    turn_count               = EXCLUDED.turn_count,
    max_internal_gap_seconds = EXCLUDED.max_internal_gap_seconds,
    status                   = EXCLUDED.status,
    bbox_last                = EXCLUDED.bbox_last,
    updated_at               = now()
RETURNING id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
          detection_count, turn_count, max_internal_gap_seconds,
          status, bbox_first, bbox_last,
          created_at, updated_at
`

type UpsertEncounterParams struct {
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
}

type UpsertEncounterRow struct {
	ID                    int64              `json:"id"`
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

// Insert-or-update an encounter row keyed on (dongle_id, route,
// plate_hash, first_seen_ts). Re-running the aggregator over the same
// route is idempotent: the unique constraint catches the conflict and
// the DO UPDATE refreshes the mutable fields (last_seen_ts,
// detection_count, turn_count, gap, status, bbox_last, updated_at).
// first_seen_ts and bbox_first are NOT updated because they identify
// the encounter and changing them would defeat idempotency.
func (q *Queries) UpsertEncounter(ctx context.Context, arg UpsertEncounterParams) (UpsertEncounterRow, error) {
	row := q.db.QueryRow(ctx, upsertEncounter,
		arg.DongleID,
		arg.Route,
		arg.PlateHash,
		arg.FirstSeenTs,
		arg.LastSeenTs,
		arg.DetectionCount,
		arg.TurnCount,
		arg.MaxInternalGapSeconds,
		arg.Status,
		arg.BboxFirst,
		arg.BboxLast,
	)
	var i UpsertEncounterRow
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.Route,
		&i.PlateHash,
		&i.FirstSeenTs,
		&i.LastSeenTs,
		&i.DetectionCount,
		&i.TurnCount,
		&i.MaxInternalGapSeconds,
		&i.Status,
		&i.BboxFirst,
		&i.BboxLast,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
