// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_detections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDetectionsOlderThan = `-- name: DeleteDetectionsOlderThan :execrows
DELETE FROM plate_detections
WHERE frame_ts < $1
`

// Retention sweep: drop every detection older than the cutoff regardless
// of watchlist state. This is the unconditional path used when the
// operator opts out of "keep evidence for flagged plates" or when the
// detection retention window is shorter than the alert evidence window.
// Returns the number of rows actually deleted.
func (q *Queries) DeleteDetectionsOlderThan(ctx context.Context, frameTs pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDetectionsOlderThan, frameTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDetectionsOlderThanForUnflagged = `-- name: DeleteDetectionsOlderThanForUnflagged :execrows
DELETE FROM plate_detections d
WHERE d.frame_ts < $1
  AND NOT EXISTS (
        SELECT 1 FROM plate_watchlist w
        WHERE w.plate_hash = d.plate_hash
  )
`

// Retention sweep variant that preserves detections whose plate_hash
// appears in plate_watchlist (whitelist or alerted). The default privacy
// posture is to forget plates aggressively except for the small subset
// the operator explicitly flagged. Returns the number of rows deleted.
func (q *Queries) DeleteDetectionsOlderThanForUnflagged(ctx context.Context, frameTs pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDetectionsOlderThanForUnflagged, frameTs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertDetection = `-- name: InsertDetection :one
INSERT INTO plate_detections (
    dongle_id,
    route,
    segment,
    frame_offset_ms,
    plate_ciphertext,
    plate_hash,
    bbox,
    confidence,
    ocr_corrected,
    gps_lat,
    gps_lng,
    gps_heading_deg,
    frame_ts,
    thumb_path
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, dongle_id, route, segment, frame_offset_ms,
          plate_ciphertext, plate_hash, bbox, confidence, ocr_corrected,
          gps_lat, gps_lng, gps_heading_deg, frame_ts, thumb_path,
          created_at
`

type InsertDetectionParams struct {
	DongleID        string             `json:"dongleId"`
	Route           string             `json:"route"`
	Segment         int32              `json:"segment"`
	FrameOffsetMs   int32              `json:"frameOffsetMs"`
	PlateCiphertext []byte             `json:"plateCiphertext"`
	PlateHash       []byte             `json:"plateHash"`
	Bbox            []byte             `json:"bbox"`
	Confidence      float32            `json:"confidence"`
	OcrCorrected    bool               `json:"ocrCorrected"`
	GpsLat          pgtype.Float8      `json:"gpsLat"`
	GpsLng          pgtype.Float8      `json:"gpsLng"`
	GpsHeadingDeg   pgtype.Float4      `json:"gpsHeadingDeg"`
	FrameTs         pgtype.Timestamptz `json:"frameTs"`
	ThumbPath       pgtype.Text        `json:"thumbPath"`
}

type InsertDetectionRow struct {
	ID              int64              `json:"id"`
	DongleID        string             `json:"dongleId"`
	Route           string             `json:"route"`
	Segment         int32              `json:"segment"`
	FrameOffsetMs   int32              `json:"frameOffsetMs"`
	PlateCiphertext []byte             `json:"plateCiphertext"`
	PlateHash       []byte             `json:"plateHash"`
	Bbox            []byte             `json:"bbox"`
	Confidence      float32            `json:"confidence"`
	OcrCorrected    bool               `json:"ocrCorrected"`
	GpsLat          pgtype.Float8      `json:"gpsLat"`
	GpsLng          pgtype.Float8      `json:"gpsLng"`
	GpsHeadingDeg   pgtype.Float4      `json:"gpsHeadingDeg"`
	FrameTs         pgtype.Timestamptz `json:"frameTs"`
	ThumbPath       pgtype.Text        `json:"thumbPath"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

// Inserts a single plate detection. Returns the freshly-allocated id and
// created_at so the caller can correlate the row to whatever in-memory
// detection it came from.
func (q *Queries) InsertDetection(ctx context.Context, arg InsertDetectionParams) (InsertDetectionRow, error) {
	row := q.db.QueryRow(ctx, insertDetection,
		arg.DongleID,
		arg.Route,
		arg.Segment,
		arg.FrameOffsetMs,
		arg.PlateCiphertext,
		arg.PlateHash,
		arg.Bbox,
		arg.Confidence,
		arg.OcrCorrected,
		arg.GpsLat,
		arg.GpsLng,
		arg.GpsHeadingDeg,
		arg.FrameTs,
		arg.ThumbPath,
	)
	var i InsertDetectionRow
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.Route,
		&i.Segment,
		&i.FrameOffsetMs,
		&i.PlateCiphertext,
		&i.PlateHash,
		&i.Bbox,
		&i.Confidence,
		&i.OcrCorrected,
		&i.GpsLat,
		&i.GpsLng,
		&i.GpsHeadingDeg,
		&i.FrameTs,
		&i.ThumbPath,
		&i.CreatedAt,
	)
	return i, err
}

const listDetectionsForRoute = `-- name: ListDetectionsForRoute :many
SELECT id, dongle_id, route, segment, frame_offset_ms,
       plate_ciphertext, plate_hash, bbox, confidence, ocr_corrected,
       gps_lat, gps_lng, gps_heading_deg, frame_ts, thumb_path,
       created_at
FROM plate_detections
WHERE dongle_id = $1 AND route = $2
ORDER BY frame_ts ASC, id ASC
`

type ListDetectionsForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

type ListDetectionsForRouteRow struct {
	ID              int64              `json:"id"`
	DongleID        string             `json:"dongleId"`
	Route           string             `json:"route"`
	Segment         int32              `json:"segment"`
	FrameOffsetMs   int32              `json:"frameOffsetMs"`
	PlateCiphertext []byte             `json:"plateCiphertext"`
	PlateHash       []byte             `json:"plateHash"`
	Bbox            []byte             `json:"bbox"`
	Confidence      float32            `json:"confidence"`
	OcrCorrected    bool               `json:"ocrCorrected"`
	GpsLat          pgtype.Float8      `json:"gpsLat"`
	GpsLng          pgtype.Float8      `json:"gpsLng"`
	GpsHeadingDeg   pgtype.Float4      `json:"gpsHeadingDeg"`
	FrameTs         pgtype.Timestamptz `json:"frameTs"`
	ThumbPath       pgtype.Text        `json:"thumbPath"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

// All detections for a single route, in chronological order. Used by the
// encounter aggregator and the per-route review UI.
func (q *Queries) ListDetectionsForRoute(ctx context.Context, arg ListDetectionsForRouteParams) ([]ListDetectionsForRouteRow, error) {
	rows, err := q.db.Query(ctx, listDetectionsForRoute, arg.DongleID, arg.Route)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDetectionsForRouteRow
	for rows.Next() {
		var i ListDetectionsForRouteRow
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.Segment,
			&i.FrameOffsetMs,
			&i.PlateCiphertext,
			&i.PlateHash,
			&i.Bbox,
			&i.Confidence,
			&i.OcrCorrected,
			&i.GpsLat,
			&i.GpsLng,
			&i.GpsHeadingDeg,
			&i.FrameTs,
			&i.ThumbPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDetectionsForRouteSince = `-- name: ListDetectionsForRouteSince :many
SELECT id, dongle_id, route, segment, frame_offset_ms,
       plate_ciphertext, plate_hash, bbox, confidence, ocr_corrected,
       gps_lat, gps_lng, gps_heading_deg, frame_ts, thumb_path,
       created_at
FROM plate_detections
WHERE dongle_id = $1
  AND route     = $2
  AND frame_ts >= $3
ORDER BY frame_ts ASC, id ASC
`

type ListDetectionsForRouteSinceParams struct {
	DongleID string             `json:"dongleId"`
	Route    string             `json:"route"`
	FrameTs  pgtype.Timestamptz `json:"frameTs"`
}

type ListDetectionsForRouteSinceRow struct {
	ID              int64              `json:"id"`
	DongleID        string             `json:"dongleId"`
	Route           string             `json:"route"`
	Segment         int32              `json:"segment"`
	FrameOffsetMs   int32              `json:"frameOffsetMs"`
	PlateCiphertext []byte             `json:"plateCiphertext"`
	PlateHash       []byte             `json:"plateHash"`
	Bbox            []byte             `json:"bbox"`
	Confidence      float32            `json:"confidence"`
	OcrCorrected    bool               `json:"ocrCorrected"`
	GpsLat          pgtype.Float8      `json:"gpsLat"`
	GpsLng          pgtype.Float8      `json:"gpsLng"`
	GpsHeadingDeg   pgtype.Float4      `json:"gpsHeadingDeg"`
	FrameTs         pgtype.Timestamptz `json:"frameTs"`
	ThumbPath       pgtype.Text        `json:"thumbPath"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

// Detections for a route at or after the given frame_ts. Used by the
// aggregator when it processes a route incrementally (segment-by-segment)
// so it does not re-scan already-aggregated detections on every pass.
func (q *Queries) ListDetectionsForRouteSince(ctx context.Context, arg ListDetectionsForRouteSinceParams) ([]ListDetectionsForRouteSinceRow, error) {
	rows, err := q.db.Query(ctx, listDetectionsForRouteSince, arg.DongleID, arg.Route, arg.FrameTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDetectionsForRouteSinceRow
	for rows.Next() {
		var i ListDetectionsForRouteSinceRow
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.Segment,
			&i.FrameOffsetMs,
			&i.PlateCiphertext,
			&i.PlateHash,
			&i.Bbox,
			&i.Confidence,
			&i.OcrCorrected,
			&i.GpsLat,
			&i.GpsLng,
			&i.GpsHeadingDeg,
			&i.FrameTs,
			&i.ThumbPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDetectionPlate = `-- name: UpdateDetectionPlate :exec
UPDATE plate_detections
SET plate_ciphertext = $2,
    plate_hash       = $3,
    ocr_corrected    = TRUE
WHERE id = $1
`

type UpdateDetectionPlateParams struct {
	ID              int64  `json:"id"`
	PlateCiphertext []byte `json:"plateCiphertext"`
	PlateHash       []byte `json:"plateHash"`
}

// Manual-correction path: replace the encrypted plate text and its hash
// on a single detection, and flip ocr_corrected to true. Both columns
// are updated together so a corrected plate text always matches its
// hash. Caller computes the new ciphertext and hash; the DB just
// persists.
func (q *Queries) UpdateDetectionPlate(ctx context.Context, arg UpdateDetectionPlateParams) error {
	_, err := q.db.Exec(ctx, updateDetectionPlate, arg.ID, arg.PlateCiphertext, arg.PlateHash)
	return err
}

const updateDetectionPlateHash = `-- name: UpdateDetectionPlateHash :execrows
UPDATE plate_detections
SET plate_hash       = $1,
    plate_ciphertext = $2
WHERE plate_hash = $3
`

type UpdateDetectionPlateHashParams struct {
	NewPlateHash       []byte `json:"newPlateHash"`
	NewPlateCiphertext []byte `json:"newPlateCiphertext"`
	OldPlateHash       []byte `json:"oldPlateHash"`
}

// Plate-merge path: rewrite plate_hash (and the matching ciphertext) on
// every detection that currently points at the source hash. Returns the
// number of rows rewritten so the merge UI can confirm the operation
// touched what it expected. Both columns are written together so the
// hash and ciphertext stay consistent.
func (q *Queries) UpdateDetectionPlateHash(ctx context.Context, arg UpdateDetectionPlateHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDetectionPlateHash, arg.NewPlateHash, arg.NewPlateCiphertext, arg.OldPlateHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDetectionSignature = `-- name: UpdateDetectionSignature :exec
UPDATE plate_detections
SET signature_id        = $1,
    det_make            = $2,
    det_model           = $3,
    det_color           = $4,
    det_body_type       = $5,
    det_attr_confidence = $6
WHERE id = $7
`

type UpdateDetectionSignatureParams struct {
	SignatureID       pgtype.Int8   `json:"signatureId"`
	DetMake           pgtype.Text   `json:"detMake"`
	DetModel          pgtype.Text   `json:"detModel"`
	DetColor          pgtype.Text   `json:"detColor"`
	DetBodyType       pgtype.Text   `json:"detBodyType"`
	DetAttrConfidence pgtype.Float4 `json:"detAttrConfidence"`
	ID                int64         `json:"id"`
}

// Stamp the signature link plus the denormalized vehicle attribute
// columns onto a single detection row. Called by the signature
// classifier after it produces a (signature_id, make, model, color,
// body_type) tuple for a frame. The denormalized columns are
// intentionally co-written with the FK so review queries that filter
// by attribute do not have to join through vehicle_signatures.
func (q *Queries) UpdateDetectionSignature(ctx context.Context, arg UpdateDetectionSignatureParams) error {
	_, err := q.db.Exec(ctx, updateDetectionSignature,
		arg.SignatureID,
		arg.DetMake,
		arg.DetModel,
		arg.DetColor,
		arg.DetBodyType,
		arg.DetAttrConfidence,
		arg.ID,
	)
	return err
}
