// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_alert_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOrphanedAlertEvents = `-- name: DeleteOrphanedAlertEvents :execrows
DELETE FROM plate_alert_events e
WHERE e.computed_at < $1
  AND NOT EXISTS (
        SELECT 1 FROM plate_watchlist w
        WHERE w.plate_hash = e.plate_hash
  )
`

// Retention sweep: drop alert events older than the supplied cutoff
// whose plate_hash is no longer in plate_watchlist. The watchlist row
// is the load-bearing record for an active alert; once an operator has
// removed it (or it was never persisted because the alert was demoted),
// the heuristic evaluations behind it become trail-only and can age out
// after a generous review window. Plates still on the watchlist keep
// their full evaluation history regardless of computed_at -- the audit
// trail is the basis for the "why is this plate alerted" UI.
// Returns the number of rows deleted.
func (q *Queries) DeleteOrphanedAlertEvents(ctx context.Context, computedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanedAlertEvents, computedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAlertEvent = `-- name: InsertAlertEvent :one
INSERT INTO plate_alert_events (
    plate_hash,
    route,
    dongle_id,
    severity,
    components,
    heuristic_version
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, plate_hash, route, dongle_id, computed_at, severity,
          components, heuristic_version
`

type InsertAlertEventParams struct {
	PlateHash        []byte      `json:"plateHash"`
	Route            pgtype.Text `json:"route"`
	DongleID         pgtype.Text `json:"dongleId"`
	Severity         int16       `json:"severity"`
	Components       []byte      `json:"components"`
	HeuristicVersion string      `json:"heuristicVersion"`
}

// Records why a heuristic decided a plate was alert-worthy. Append-only;
// this table is never touched by retention sweeps because it is the
// evidence trail behind every alert badge the operator might later
// review.
func (q *Queries) InsertAlertEvent(ctx context.Context, arg InsertAlertEventParams) (PlateAlertEvent, error) {
	row := q.db.QueryRow(ctx, insertAlertEvent,
		arg.PlateHash,
		arg.Route,
		arg.DongleID,
		arg.Severity,
		arg.Components,
		arg.HeuristicVersion,
	)
	var i PlateAlertEvent
	err := row.Scan(
		&i.ID,
		&i.PlateHash,
		&i.Route,
		&i.DongleID,
		&i.ComputedAt,
		&i.Severity,
		&i.Components,
		&i.HeuristicVersion,
	)
	return i, err
}

const listEventsForPlate = `-- name: ListEventsForPlate :many
SELECT id, plate_hash, route, dongle_id, computed_at, severity,
       components, heuristic_version
FROM plate_alert_events
WHERE plate_hash = $1
ORDER BY computed_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListEventsForPlateParams struct {
	PlateHash []byte `json:"plateHash"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

// Paginated list of every heuristic evaluation for a plate, newest
// first. Powers the "why is this plate alerted" drill-down on the plate
// detail page.
func (q *Queries) ListEventsForPlate(ctx context.Context, arg ListEventsForPlateParams) ([]PlateAlertEvent, error) {
	rows, err := q.db.Query(ctx, listEventsForPlate, arg.PlateHash, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlateAlertEvent
	for rows.Next() {
		var i PlateAlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.PlateHash,
			&i.Route,
			&i.DongleID,
			&i.ComputedAt,
			&i.Severity,
			&i.Components,
			&i.HeuristicVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
