// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_segment_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const isExtractorProcessed = `-- name: IsExtractorProcessed :one
SELECT COALESCE(
    (SELECT processed_at_extractor IS NOT NULL
     FROM alpr_segment_progress
     WHERE dongle_id = $1 AND route = $2 AND segment = $3),
    FALSE
)::BOOLEAN AS processed
`

type IsExtractorProcessedParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
	Segment  int32  `json:"segment"`
}

// Quick yes/no check for whether a single segment has been processed by
// the frame extractor. The worker calls this before downloading the
// segment's video to avoid redundant work after a crash/restart. Returns
// false when the row does not exist.
func (q *Queries) IsExtractorProcessed(ctx context.Context, arg IsExtractorProcessedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isExtractorProcessed, arg.DongleID, arg.Route, arg.Segment)
	var processed bool
	err := row.Scan(&processed)
	return processed, err
}

const listUnprocessedSegments = `-- name: ListUnprocessedSegments :many
SELECT dongle_id, route, segment,
       processed_at_extractor, processed_at_detector
FROM alpr_segment_progress
WHERE dongle_id = $1
  AND route     = $2
  AND (($3::BOOLEAN = TRUE
        AND processed_at_extractor IS NULL)
    OR ($4::BOOLEAN  = TRUE
        AND processed_at_detector  IS NULL))
ORDER BY segment ASC
`

type ListUnprocessedSegmentsParams struct {
	DongleID         string `json:"dongleId"`
	Route            string `json:"route"`
	RequireExtractor bool   `json:"requireExtractor"`
	RequireDetector  bool   `json:"requireDetector"`
}

// Returns segments inside (or adjacent to) the route whose extractor or
// detector pass has not yet completed. The frame extractor and the
// detector both call this with the appropriate filter to find work.
// Pass require_extractor=true to find segments missing the extractor
// pass; pass require_detector=true to find segments missing the
// detector pass. Both filters can be combined.
func (q *Queries) ListUnprocessedSegments(ctx context.Context, arg ListUnprocessedSegmentsParams) ([]AlprSegmentProgress, error) {
	rows, err := q.db.Query(ctx, listUnprocessedSegments,
		arg.DongleID,
		arg.Route,
		arg.RequireExtractor,
		arg.RequireDetector,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlprSegmentProgress
	for rows.Next() {
		var i AlprSegmentProgress
		if err := rows.Scan(
			&i.DongleID,
			&i.Route,
			&i.Segment,
			&i.ProcessedAtExtractor,
			&i.ProcessedAtDetector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDetectorProcessed = `-- name: MarkDetectorProcessed :exec
INSERT INTO alpr_segment_progress (
    dongle_id, route, segment, processed_at_detector
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (dongle_id, route, segment) DO UPDATE
SET processed_at_detector = EXCLUDED.processed_at_detector
`

type MarkDetectorProcessedParams struct {
	DongleID            string             `json:"dongleId"`
	Route               string             `json:"route"`
	Segment             int32              `json:"segment"`
	ProcessedAtDetector pgtype.Timestamptz `json:"processedAtDetector"`
}

// Records that the detector stage finished a segment. Same idempotent
// pattern as MarkExtractorProcessed but for the detector column.
func (q *Queries) MarkDetectorProcessed(ctx context.Context, arg MarkDetectorProcessedParams) error {
	_, err := q.db.Exec(ctx, markDetectorProcessed,
		arg.DongleID,
		arg.Route,
		arg.Segment,
		arg.ProcessedAtDetector,
	)
	return err
}

const markExtractorProcessed = `-- name: MarkExtractorProcessed :exec
INSERT INTO alpr_segment_progress (
    dongle_id, route, segment, processed_at_extractor
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (dongle_id, route, segment) DO UPDATE
SET processed_at_extractor = EXCLUDED.processed_at_extractor
`

type MarkExtractorProcessedParams struct {
	DongleID             string             `json:"dongleId"`
	Route                string             `json:"route"`
	Segment              int32              `json:"segment"`
	ProcessedAtExtractor pgtype.Timestamptz `json:"processedAtExtractor"`
}

// Records that the frame-extractor stage finished a segment. Idempotent:
// a re-run sets processed_at_extractor to the latest invocation, leaving
// processed_at_detector untouched.
func (q *Queries) MarkExtractorProcessed(ctx context.Context, arg MarkExtractorProcessedParams) error {
	_, err := q.db.Exec(ctx, markExtractorProcessed,
		arg.DongleID,
		arg.Route,
		arg.Segment,
		arg.ProcessedAtExtractor,
	)
	return err
}
