// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_notifications_sent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLastNotificationSent = `-- name: GetLastNotificationSent :one

SELECT plate_hash, last_sent_at
FROM alpr_notifications_sent
WHERE plate_hash = $1
`

// Queries for the ALPR notify-dispatcher dedup ledger. The schema lives
// in 019_alpr_notifications_sent.up.sql. The dispatcher reads
// last_sent_at to decide whether the dedup window has elapsed and writes
// a fresh row (or refreshes an existing one) every time at least one
// sender succeeded.
// Returns the most recent send timestamp for a plate hash. The dispatcher
// compares (now() - last_sent_at) against the configured dedup window;
// a missing row (pgx.ErrNoRows) means "never sent for this plate" and the
// caller proceeds with dispatch.
func (q *Queries) GetLastNotificationSent(ctx context.Context, plateHash []byte) (AlprNotificationsSent, error) {
	row := q.db.QueryRow(ctx, getLastNotificationSent, plateHash)
	var i AlprNotificationsSent
	err := row.Scan(&i.PlateHash, &i.LastSentAt)
	return i, err
}

const upsertNotificationSent = `-- name: UpsertNotificationSent :exec
INSERT INTO alpr_notifications_sent (plate_hash, last_sent_at)
VALUES ($1, $2)
ON CONFLICT (plate_hash) DO UPDATE
    SET last_sent_at = EXCLUDED.last_sent_at
`

type UpsertNotificationSentParams struct {
	PlateHash  []byte             `json:"plateHash"`
	LastSentAt pgtype.Timestamptz `json:"lastSentAt"`
}

// Inserts a fresh ledger row or refreshes the timestamp of an existing
// one. The PRIMARY KEY conflict path bumps last_sent_at to the supplied
// time so the dedup window is measured from the most recent successful
// dispatch (not the first one). The caller passes time.Now() explicitly
// so tests can pin wall time deterministically.
func (q *Queries) UpsertNotificationSent(ctx context.Context, arg UpsertNotificationSentParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationSent, arg.PlateHash, arg.LastSentAt)
	return err
}
