// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_backfill_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBackfillRoutes = `-- name: CountBackfillRoutes :one
SELECT COUNT(*)::BIGINT AS total
FROM routes r
WHERE ($1::TIMESTAMPTZ IS NULL
       OR r.start_time >= $1::TIMESTAMPTZ)
  AND ($2::TIMESTAMPTZ IS NULL
       OR r.start_time <  $2::TIMESTAMPTZ)
  AND ($3::TEXT IS NULL
       OR r.dongle_id = $3::TEXT)
  AND ($4::TEXT IS NULL
       OR r.route_name > $4::TEXT)
`

type CountBackfillRoutesParams struct {
	FromDate   pgtype.Timestamptz `json:"fromDate"`
	ToDate     pgtype.Timestamptz `json:"toDate"`
	DongleID   pgtype.Text        `json:"dongleId"`
	AfterRoute pgtype.Text        `json:"afterRoute"`
}

// Returns the number of routes that match the start-request filter
// set, used to seed total_routes on insert. Pass NULL for from_date /
// to_date / dongle_id to disable that filter; pass 0 for max_routes
// to disable the cap (matches the "unlimited" semantics callers
// expect from omitted JSON fields). NULL filter args are evaluated
// against the routes table without referencing trips so a fresh
// install with no aggregated trips still counts correctly.
func (q *Queries) CountBackfillRoutes(ctx context.Context, arg CountBackfillRoutesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBackfillRoutes,
		arg.FromDate,
		arg.ToDate,
		arg.DongleID,
		arg.AfterRoute,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getBackfillJob = `-- name: GetBackfillJob :one
SELECT id, started_at, finished_at, state, filters_json,
       total_routes, processed_routes, last_processed_route,
       error, started_by
FROM alpr_backfill_jobs
WHERE id = $1
`

// Fetches a single job row by id. Used by the worker on restart to
// re-read state mid-loop (pause / resume / cancel cooperative checks).
func (q *Queries) GetBackfillJob(ctx context.Context, id int64) (AlprBackfillJob, error) {
	row := q.db.QueryRow(ctx, getBackfillJob, id)
	var i AlprBackfillJob
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.State,
		&i.FiltersJson,
		&i.TotalRoutes,
		&i.ProcessedRoutes,
		&i.LastProcessedRoute,
		&i.Error,
		&i.StartedBy,
	)
	return i, err
}

const getLatestBackfillJob = `-- name: GetLatestBackfillJob :one
SELECT id, started_at, finished_at, state, filters_json,
       total_routes, processed_routes, last_processed_route,
       error, started_by
FROM alpr_backfill_jobs
ORDER BY started_at DESC, id DESC
LIMIT 1
`

// Returns the most-recently started job row. The status endpoint
// (GET /v1/alpr/backfill/status) returns this, regardless of state.
// Returns sql.ErrNoRows when no job has ever been recorded; the API
// handler maps that to a 200 with an empty job envelope.
func (q *Queries) GetLatestBackfillJob(ctx context.Context) (AlprBackfillJob, error) {
	row := q.db.QueryRow(ctx, getLatestBackfillJob)
	var i AlprBackfillJob
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.State,
		&i.FiltersJson,
		&i.TotalRoutes,
		&i.ProcessedRoutes,
		&i.LastProcessedRoute,
		&i.Error,
		&i.StartedBy,
	)
	return i, err
}

const getRunningBackfillJob = `-- name: GetRunningBackfillJob :one
SELECT id, started_at, finished_at, state, filters_json,
       total_routes, processed_routes, last_processed_route,
       error, started_by
FROM alpr_backfill_jobs
WHERE state = 'running'
LIMIT 1
`

// Returns the job currently in state='running', if any. The worker
// calls this on startup to find the row to resume; the start handler
// can use it as a pre-check before INSERT (the partial unique index is
// still authoritative -- this is a fast-path).
func (q *Queries) GetRunningBackfillJob(ctx context.Context) (AlprBackfillJob, error) {
	row := q.db.QueryRow(ctx, getRunningBackfillJob)
	var i AlprBackfillJob
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.State,
		&i.FiltersJson,
		&i.TotalRoutes,
		&i.ProcessedRoutes,
		&i.LastProcessedRoute,
		&i.Error,
		&i.StartedBy,
	)
	return i, err
}

const incrementBackfillJobProgress = `-- name: IncrementBackfillJobProgress :exec
UPDATE alpr_backfill_jobs
SET processed_routes     = processed_routes + 1,
    last_processed_route = $2
WHERE id = $1
`

type IncrementBackfillJobProgressParams struct {
	ID                 int64       `json:"id"`
	LastProcessedRoute pgtype.Text `json:"lastProcessedRoute"`
}

// Bumps processed_routes by 1 and stamps last_processed_route after a
// route's segments have all been enqueued (or skipped for being
// already complete). Atomic so the worker's progress and resume token
// can never disagree across a crash.
func (q *Queries) IncrementBackfillJobProgress(ctx context.Context, arg IncrementBackfillJobProgressParams) error {
	_, err := q.db.Exec(ctx, incrementBackfillJobProgress, arg.ID, arg.LastProcessedRoute)
	return err
}

const insertBackfillJob = `-- name: InsertBackfillJob :one

INSERT INTO alpr_backfill_jobs (
    state, filters_json, total_routes, started_by
)
VALUES ($1, $2, $3, $4)
RETURNING id, started_at, finished_at, state, filters_json,
          total_routes, processed_routes, last_processed_route,
          error, started_by
`

type InsertBackfillJobParams struct {
	State       string      `json:"state"`
	FiltersJson []byte      `json:"filtersJson"`
	TotalRoutes pgtype.Int4 `json:"totalRoutes"`
	StartedBy   pgtype.Text `json:"startedBy"`
}

// Queries for the ALPR historical backfill jobs table. The schema lives
// in 017_alpr_backfill_jobs.up.sql. There is at most one row in
// state='running' at a time (enforced by the partial unique index
// alpr_backfill_jobs_one_running); the unique-violation that an
// attempted second running INSERT trips on is what the API handler
// maps to 409 Conflict.
// Inserts a fresh job row in the requested state. Callers pass
// state='running' to start the worker immediately (the partial unique
// index then guards against a parallel start). filters_json is the
// parsed start-request body. total_routes is computed by the API
// handler (CountBackfillRoutes) before the insert so the worker has a
// stable denominator for progress / ETA.
func (q *Queries) InsertBackfillJob(ctx context.Context, arg InsertBackfillJobParams) (AlprBackfillJob, error) {
	row := q.db.QueryRow(ctx, insertBackfillJob,
		arg.State,
		arg.FiltersJson,
		arg.TotalRoutes,
		arg.StartedBy,
	)
	var i AlprBackfillJob
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.State,
		&i.FiltersJson,
		&i.TotalRoutes,
		&i.ProcessedRoutes,
		&i.LastProcessedRoute,
		&i.Error,
		&i.StartedBy,
	)
	return i, err
}

const listBackfillRoutesAsc = `-- name: ListBackfillRoutesAsc :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry,
       created_at, preserved, note, starred, geometry_times
FROM routes r
WHERE ($2::TIMESTAMPTZ IS NULL
       OR r.start_time >= $2::TIMESTAMPTZ)
  AND ($3::TIMESTAMPTZ IS NULL
       OR r.start_time <  $3::TIMESTAMPTZ)
  AND ($4::TEXT IS NULL
       OR r.dongle_id = $4::TEXT)
  AND ($5::TEXT IS NULL
       OR r.route_name > $5::TEXT)
ORDER BY r.route_name ASC, r.id ASC
LIMIT $1
`

type ListBackfillRoutesAscParams struct {
	Limit      int32              `json:"limit"`
	FromDate   pgtype.Timestamptz `json:"fromDate"`
	ToDate     pgtype.Timestamptz `json:"toDate"`
	DongleID   pgtype.Text        `json:"dongleId"`
	AfterRoute pgtype.Text        `json:"afterRoute"`
}

// Lists routes for the worker to process in chronological order
// (oldest first). Filters mirror CountBackfillRoutes. after_route is
// the resume token: pass last_processed_route to skip routes already
// handled by an earlier pass of the same job. Pass NULL for any
// filter to disable it. Limit caps the slice the worker walks per
// batch -- the worker re-queries with the new last_processed_route
// after each batch so a server crash mid-batch resumes correctly.
func (q *Queries) ListBackfillRoutesAsc(ctx context.Context, arg ListBackfillRoutesAscParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listBackfillRoutesAsc,
		arg.Limit,
		arg.FromDate,
		arg.ToDate,
		arg.DongleID,
		arg.AfterRoute,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
			&i.Note,
			&i.Starred,
			&i.GeometryTimes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBackfillRoutesDesc = `-- name: ListBackfillRoutesDesc :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry,
       created_at, preserved, note, starred, geometry_times
FROM routes r
WHERE ($2::TIMESTAMPTZ IS NULL
       OR r.start_time >= $2::TIMESTAMPTZ)
  AND ($3::TIMESTAMPTZ IS NULL
       OR r.start_time <  $3::TIMESTAMPTZ)
  AND ($4::TEXT IS NULL
       OR r.dongle_id = $4::TEXT)
  AND ($5::TEXT IS NULL
       OR r.route_name < $5::TEXT)
ORDER BY r.route_name DESC, r.id DESC
LIMIT $1
`

type ListBackfillRoutesDescParams struct {
	Limit      int32              `json:"limit"`
	FromDate   pgtype.Timestamptz `json:"fromDate"`
	ToDate     pgtype.Timestamptz `json:"toDate"`
	DongleID   pgtype.Text        `json:"dongleId"`
	AfterRoute pgtype.Text        `json:"afterRoute"`
}

// Same as ListBackfillRoutesAsc but newest first. The newest_first
// knob in the start-request filter selects between the two.
// after_route here means "route_name strictly less than this token"
// so the resume sequence still moves monotonically toward older
// routes.
func (q *Queries) ListBackfillRoutesDesc(ctx context.Context, arg ListBackfillRoutesDescParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listBackfillRoutesDesc,
		arg.Limit,
		arg.FromDate,
		arg.ToDate,
		arg.DongleID,
		arg.AfterRoute,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
			&i.Note,
			&i.Starred,
			&i.GeometryTimes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBackfillJobState = `-- name: UpdateBackfillJobState :exec
UPDATE alpr_backfill_jobs
SET state       = $2,
    finished_at = COALESCE($3::TIMESTAMPTZ, finished_at),
    error       = COALESCE($4::TEXT, error)
WHERE id = $1
`

type UpdateBackfillJobStateParams struct {
	ID         int64              `json:"id"`
	State      string             `json:"state"`
	FinishedAt pgtype.Timestamptz `json:"finishedAt"`
	ErrorText  pgtype.Text        `json:"errorText"`
}

// Updates the state column on a job row. The API handlers (pause /
// resume / cancel) and the worker (transition to 'paused' on
// alpr_enabled=false, 'done' on completion, 'failed' on hard error)
// all funnel through here. finished_at is set by the caller iff state
// moves to a terminal value (done/failed); pass a NULL otherwise so
// the column stays NULL until termination.
func (q *Queries) UpdateBackfillJobState(ctx context.Context, arg UpdateBackfillJobStateParams) error {
	_, err := q.db.Exec(ctx, updateBackfillJobState,
		arg.ID,
		arg.State,
		arg.FinishedAt,
		arg.ErrorText,
	)
	return err
}
