// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_encounters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEncountersForRoute = `-- name: DeleteEncountersForRoute :execrows
DELETE FROM plate_encounters
WHERE dongle_id = $1 AND route = $2
`

type DeleteEncountersForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

// Wipe the encounter rows for one route. The aggregator calls this
// before re-running over a route so the new pass starts from a clean
// slate. Returns the number of rows deleted so the caller can log how
// much state it discarded.
func (q *Queries) DeleteEncountersForRoute(ctx context.Context, arg DeleteEncountersForRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEncountersForRoute, arg.DongleID, arg.Route)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOrphanedEncounters = `-- name: DeleteOrphanedEncounters :execrows
DELETE FROM plate_encounters pe
WHERE NOT EXISTS (
        SELECT 1
        FROM plate_detections d
        WHERE d.dongle_id  = pe.dongle_id
          AND d.route      = pe.route
          AND d.plate_hash = pe.plate_hash
          AND d.frame_ts BETWEEN pe.first_seen_ts AND pe.last_seen_ts
  )
`

// Retention sweep: drop encounter rows whose underlying detections have
// already been pruned. After the per-detection retention pass runs, an
// encounter whose entire (first_seen_ts, last_seen_ts) window has been
// emptied of detections has no evidence left and should be cleaned up
// to keep the per-route review UI from showing zombie rows.
//
// Match semantics: an encounter survives if ANY detection still exists
// with the same (dongle_id, route, plate_hash) AND a frame_ts inside
// the encounter's [first_seen_ts, last_seen_ts] window. The plate_hash
// column scopes the join so an encounter for plate A is not kept alive
// by detections of plate B that happen to overlap in time.
// Returns the number of orphan encounter rows deleted.
func (q *Queries) DeleteOrphanedEncounters(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrphanedEncounters)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listEncountersForPlate = `-- name: ListEncountersForPlate :many
SELECT id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
       detection_count, turn_count, max_internal_gap_seconds,
       signature_id, status, bbox_first, bbox_last,
       created_at, updated_at
FROM plate_encounters
WHERE plate_hash = $1
ORDER BY last_seen_ts DESC, id DESC
`

// All encounters of a single plate across every route, newest first.
// Backs the plate-detail page and feeds the stalking heuristic's
// "recurring plate" lookups.
func (q *Queries) ListEncountersForPlate(ctx context.Context, plateHash []byte) ([]PlateEncounter, error) {
	rows, err := q.db.Query(ctx, listEncountersForPlate, plateHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlateEncounter
	for rows.Next() {
		var i PlateEncounter
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.SignatureID,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForPlateInWindow = `-- name: ListEncountersForPlateInWindow :many
SELECT id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
       detection_count, turn_count, max_internal_gap_seconds,
       signature_id, status, bbox_first, bbox_last,
       created_at, updated_at
FROM plate_encounters
WHERE plate_hash    = $1
  AND last_seen_ts >= $2
  AND first_seen_ts <= $3
ORDER BY last_seen_ts DESC, id DESC
`

type ListEncountersForPlateInWindowParams struct {
	PlateHash   []byte             `json:"plateHash"`
	LastSeenTs  pgtype.Timestamptz `json:"lastSeenTs"`
	FirstSeenTs pgtype.Timestamptz `json:"firstSeenTs"`
}

// Encounters for a plate that overlap a given time window. The window is
// inclusive on both ends. Used by the stalking heuristic to count how
// many recent times the suspect plate was seen, without paging through
// the entire history.
func (q *Queries) ListEncountersForPlateInWindow(ctx context.Context, arg ListEncountersForPlateInWindowParams) ([]PlateEncounter, error) {
	rows, err := q.db.Query(ctx, listEncountersForPlateInWindow, arg.PlateHash, arg.LastSeenTs, arg.FirstSeenTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlateEncounter
	for rows.Next() {
		var i PlateEncounter
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.SignatureID,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForPlateInWindowWithStartGPS = `-- name: ListEncountersForPlateInWindowWithStartGPS :many
SELECT pe.id, pe.dongle_id, pe.route, pe.plate_hash,
       pe.first_seen_ts, pe.last_seen_ts,
       pe.detection_count, pe.turn_count, pe.max_internal_gap_seconds,
       pe.signature_id, pe.status, pe.bbox_first, pe.bbox_last,
       pe.created_at, pe.updated_at,
       pd.gps_lat AS start_lat,
       pd.gps_lng AS start_lng
FROM plate_encounters pe
LEFT JOIN LATERAL (
    SELECT gps_lat, gps_lng
    FROM plate_detections d
    WHERE d.dongle_id  = pe.dongle_id
      AND d.route      = pe.route
      AND d.plate_hash = pe.plate_hash
      AND d.frame_ts   = pe.first_seen_ts
    LIMIT 1
) pd ON TRUE
WHERE pe.plate_hash    = $1
  AND pe.last_seen_ts >= $2
  AND pe.first_seen_ts <= $3
ORDER BY pe.last_seen_ts DESC, pe.id DESC
`

type ListEncountersForPlateInWindowWithStartGPSParams struct {
	PlateHash   []byte             `json:"plateHash"`
	LastSeenTs  pgtype.Timestamptz `json:"lastSeenTs"`
	FirstSeenTs pgtype.Timestamptz `json:"firstSeenTs"`
}

type ListEncountersForPlateInWindowWithStartGPSRow struct {
	ID                    int64              `json:"id"`
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	SignatureID           pgtype.Int8        `json:"signatureId"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
	StartLat              pgtype.Float8      `json:"startLat"`
	StartLng              pgtype.Float8      `json:"startLng"`
}

// Same window scan as ListEncountersForPlateInWindow but joined with the
// plate's first-detection GPS for that encounter. The stalking heuristic
// needs the start coordinates of each encounter to bucket them into geo
// cells (cross_route_geo_spread); without the join it would have to
// issue one detection lookup per encounter.
//
// LEFT JOIN: an encounter without a matching detection at first_seen_ts
// (extremely rare, but possible after a manual correction or partial
// delete) still appears with NULL gps fields; the heuristic treats those
// as "no GPS" rather than dropping the encounter.
func (q *Queries) ListEncountersForPlateInWindowWithStartGPS(ctx context.Context, arg ListEncountersForPlateInWindowWithStartGPSParams) ([]ListEncountersForPlateInWindowWithStartGPSRow, error) {
	rows, err := q.db.Query(ctx, listEncountersForPlateInWindowWithStartGPS, arg.PlateHash, arg.LastSeenTs, arg.FirstSeenTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEncountersForPlateInWindowWithStartGPSRow
	for rows.Next() {
		var i ListEncountersForPlateInWindowWithStartGPSRow
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.SignatureID,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartLat,
			&i.StartLng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForRoute = `-- name: ListEncountersForRoute :many
SELECT id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
       detection_count, turn_count, max_internal_gap_seconds,
       signature_id, status, bbox_first, bbox_last,
       created_at, updated_at
FROM plate_encounters
WHERE dongle_id = $1 AND route = $2
ORDER BY first_seen_ts ASC, id ASC
`

type ListEncountersForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

// All encounter rows for a route, ordered by first_seen_ts. Powers the
// per-route review UI ("which plates did we see on this drive").
func (q *Queries) ListEncountersForRoute(ctx context.Context, arg ListEncountersForRouteParams) ([]PlateEncounter, error) {
	rows, err := q.db.Query(ctx, listEncountersForRoute, arg.DongleID, arg.Route)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlateEncounter
	for rows.Next() {
		var i PlateEncounter
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.SignatureID,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEncountersForSignatureInArea = `-- name: ListEncountersForSignatureInArea :many
SELECT pe.id, pe.dongle_id, pe.route, pe.plate_hash, pe.first_seen_ts,
       pe.last_seen_ts, pe.detection_count, pe.turn_count,
       pe.max_internal_gap_seconds, pe.signature_id, pe.status,
       pe.bbox_first, pe.bbox_last, pe.created_at, pe.updated_at
FROM plate_encounters pe
JOIN plate_detections pd ON pd.dongle_id = pe.dongle_id
                        AND pd.route     = pe.route
                        AND pd.plate_hash = pe.plate_hash
                        AND pd.frame_ts  = pe.first_seen_ts
WHERE pe.signature_id = $1
  AND pd.gps_lat BETWEEN $2 AND $3
  AND pd.gps_lng BETWEEN $4 AND $5
ORDER BY pe.last_seen_ts DESC, pe.id DESC
`

type ListEncountersForSignatureInAreaParams struct {
	SignatureID pgtype.Int8   `json:"signatureId"`
	MinLat      pgtype.Float8 `json:"minLat"`
	MaxLat      pgtype.Float8 `json:"maxLat"`
	MinLng      pgtype.Float8 `json:"minLng"`
	MaxLng      pgtype.Float8 `json:"maxLng"`
}

// Encounters linked to a vehicle signature whose first detection lies
// inside a lat/lng bounding box. Used by the signature-fusion heuristic
// to find "the same vehicle (by signature) showing up in our area" even
// across partial plate observations. The bbox is supplied as four
// scalars rather than a PostGIS geometry to keep this query independent
// of the signature schema's geometry columns.
func (q *Queries) ListEncountersForSignatureInArea(ctx context.Context, arg ListEncountersForSignatureInAreaParams) ([]PlateEncounter, error) {
	rows, err := q.db.Query(ctx, listEncountersForSignatureInArea,
		arg.SignatureID,
		arg.MinLat,
		arg.MaxLat,
		arg.MinLng,
		arg.MaxLng,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlateEncounter
	for rows.Next() {
		var i PlateEncounter
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.PlateHash,
			&i.FirstSeenTs,
			&i.LastSeenTs,
			&i.DetectionCount,
			&i.TurnCount,
			&i.MaxInternalGapSeconds,
			&i.SignatureID,
			&i.Status,
			&i.BboxFirst,
			&i.BboxLast,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEncounter = `-- name: UpsertEncounter :one
INSERT INTO plate_encounters (
    dongle_id,
    route,
    plate_hash,
    first_seen_ts,
    last_seen_ts,
    detection_count,
    turn_count,
    max_internal_gap_seconds,
    signature_id,
    status,
    bbox_first,
    bbox_last
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (dongle_id, route, plate_hash, first_seen_ts) DO UPDATE
SET last_seen_ts             = EXCLUDED.last_seen_ts,
    detection_count          = EXCLUDED.detection_count,
    turn_count               = EXCLUDED.turn_count,
    max_internal_gap_seconds = EXCLUDED.max_internal_gap_seconds,
    signature_id             = EXCLUDED.signature_id,
    status                   = EXCLUDED.status,
    bbox_last                = EXCLUDED.bbox_last,
    updated_at               = now()
RETURNING id, dongle_id, route, plate_hash, first_seen_ts, last_seen_ts,
          detection_count, turn_count, max_internal_gap_seconds,
          signature_id, status, bbox_first, bbox_last,
          created_at, updated_at
`

type UpsertEncounterParams struct {
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	SignatureID           pgtype.Int8        `json:"signatureId"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
}

// Insert-or-update an encounter row keyed on (dongle_id, route,
// plate_hash, first_seen_ts). Re-running the aggregator over the same
// route is idempotent: the unique constraint catches the conflict and
// the DO UPDATE refreshes the mutable fields (last_seen_ts,
// detection_count, turn_count, gap, signature_id, status, bbox_last,
// updated_at). first_seen_ts and bbox_first are NOT updated because
// they identify the encounter and changing them would defeat
// idempotency.
func (q *Queries) UpsertEncounter(ctx context.Context, arg UpsertEncounterParams) (PlateEncounter, error) {
	row := q.db.QueryRow(ctx, upsertEncounter,
		arg.DongleID,
		arg.Route,
		arg.PlateHash,
		arg.FirstSeenTs,
		arg.LastSeenTs,
		arg.DetectionCount,
		arg.TurnCount,
		arg.MaxInternalGapSeconds,
		arg.SignatureID,
		arg.Status,
		arg.BboxFirst,
		arg.BboxLast,
	)
	var i PlateEncounter
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.Route,
		&i.PlateHash,
		&i.FirstSeenTs,
		&i.LastSeenTs,
		&i.DetectionCount,
		&i.TurnCount,
		&i.MaxInternalGapSeconds,
		&i.SignatureID,
		&i.Status,
		&i.BboxFirst,
		&i.BboxLast,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
