// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alpr_audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :one
INSERT INTO alpr_audit_log (action, actor, payload)
VALUES ($1, $2, $3)
RETURNING id, action, actor, payload, created_at
`

type InsertAuditParams struct {
	Action  string      `json:"action"`
	Actor   pgtype.Text `json:"actor"`
	Payload []byte      `json:"payload"`
}

// Append an audit-log entry for an ALPR admin action. Returns the row so
// the caller can echo the assigned id and created_at to the operator
// (useful for the "show recent admin actions" UI).
func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) (AlprAuditLog, error) {
	row := q.db.QueryRow(ctx, insertAudit, arg.Action, arg.Actor, arg.Payload)
	var i AlprAuditLog
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.Actor,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAudit = `-- name: ListAudit :many
SELECT id, action, actor, payload, created_at
FROM alpr_audit_log
WHERE ($3::TEXT IS NULL
       OR action = $3::TEXT)
  AND ($4::TEXT  IS NULL
       OR actor  = $4::TEXT)
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAuditParams struct {
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
	ActionFilter pgtype.Text `json:"actionFilter"`
	ActorFilter  pgtype.Text `json:"actorFilter"`
}

// Paginated audit log, newest first, with optional filters. Pass NULL
// for @action_filter to disable that filter; same for @actor_filter.
// The watchlist API and tuning UI both use this view, narrowing on the
// relevant action set client-side or via the action filter.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]AlprAuditLog, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.Limit,
		arg.Offset,
		arg.ActionFilter,
		arg.ActorFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlprAuditLog
	for rows.Next() {
		var i AlprAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.Actor,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
