// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crashes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCrashes = `-- name: CountCrashes :one
SELECT COUNT(*)
FROM crashes
WHERE ($1::TEXT = ''
       OR dongle_id = $1::TEXT)
`

func (q *Queries) CountCrashes(ctx context.Context, dongleIDFilter string) (int64, error) {
	row := q.db.QueryRow(ctx, countCrashes, dongleIDFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCrash = `-- name: GetCrash :one
SELECT id, event_id, dongle_id, level, message, fingerprint,
       tags, exception, breadcrumbs, raw_event, occurred_at, received_at
FROM crashes
WHERE id = $1
`

func (q *Queries) GetCrash(ctx context.Context, id int32) (Crash, error) {
	row := q.db.QueryRow(ctx, getCrash, id)
	var i Crash
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DongleID,
		&i.Level,
		&i.Message,
		&i.Fingerprint,
		&i.Tags,
		&i.Exception,
		&i.Breadcrumbs,
		&i.RawEvent,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const insertCrash = `-- name: InsertCrash :one
INSERT INTO crashes (
    event_id, dongle_id, level, message, fingerprint,
    tags, exception, breadcrumbs, raw_event, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, event_id, dongle_id, level, message, fingerprint,
          tags, exception, breadcrumbs, raw_event, occurred_at, received_at
`

type InsertCrashParams struct {
	EventID     string             `json:"eventId"`
	DongleID    pgtype.Text        `json:"dongleId"`
	Level       string             `json:"level"`
	Message     string             `json:"message"`
	Fingerprint []byte             `json:"fingerprint"`
	Tags        []byte             `json:"tags"`
	Exception   []byte             `json:"exception"`
	Breadcrumbs []byte             `json:"breadcrumbs"`
	RawEvent    []byte             `json:"rawEvent"`
	OccurredAt  pgtype.Timestamptz `json:"occurredAt"`
}

func (q *Queries) InsertCrash(ctx context.Context, arg InsertCrashParams) (Crash, error) {
	row := q.db.QueryRow(ctx, insertCrash,
		arg.EventID,
		arg.DongleID,
		arg.Level,
		arg.Message,
		arg.Fingerprint,
		arg.Tags,
		arg.Exception,
		arg.Breadcrumbs,
		arg.RawEvent,
		arg.OccurredAt,
	)
	var i Crash
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.DongleID,
		&i.Level,
		&i.Message,
		&i.Fingerprint,
		&i.Tags,
		&i.Exception,
		&i.Breadcrumbs,
		&i.RawEvent,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const listCrashes = `-- name: ListCrashes :many
SELECT id, event_id, dongle_id, level, message, fingerprint,
       tags, exception, breadcrumbs, occurred_at, received_at
FROM crashes
WHERE ($3::TEXT = ''
       OR dongle_id = $3::TEXT)
ORDER BY received_at DESC
LIMIT $1 OFFSET $2
`

type ListCrashesParams struct {
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
	DongleIDFilter string `json:"dongleIdFilter"`
}

type ListCrashesRow struct {
	ID          int32              `json:"id"`
	EventID     string             `json:"eventId"`
	DongleID    pgtype.Text        `json:"dongleId"`
	Level       string             `json:"level"`
	Message     string             `json:"message"`
	Fingerprint []byte             `json:"fingerprint"`
	Tags        []byte             `json:"tags"`
	Exception   []byte             `json:"exception"`
	Breadcrumbs []byte             `json:"breadcrumbs"`
	OccurredAt  pgtype.Timestamptz `json:"occurredAt"`
	ReceivedAt  pgtype.Timestamptz `json:"receivedAt"`
}

// Paginated crash list with optional dongle_id filter. Pass an empty
// string for dongleID to skip the filter; a non-empty value restricts
// to a single device.
func (q *Queries) ListCrashes(ctx context.Context, arg ListCrashesParams) ([]ListCrashesRow, error) {
	rows, err := q.db.Query(ctx, listCrashes, arg.Limit, arg.Offset, arg.DongleIDFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrashesRow
	for rows.Next() {
		var i ListCrashesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.DongleID,
			&i.Level,
			&i.Message,
			&i.Fingerprint,
			&i.Tags,
			&i.Exception,
			&i.Breadcrumbs,
			&i.OccurredAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
