// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device_params.sql

package db

import (
	"context"
)

const deleteDeviceParam = `-- name: DeleteDeviceParam :exec
DELETE FROM device_params
WHERE dongle_id = $1 AND key = $2
`

type DeleteDeviceParamParams struct {
	DongleID string `json:"dongleId"`
	Key      string `json:"key"`
}

func (q *Queries) DeleteDeviceParam(ctx context.Context, arg DeleteDeviceParamParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceParam, arg.DongleID, arg.Key)
	return err
}

const getDeviceParam = `-- name: GetDeviceParam :one
SELECT id, dongle_id, key, value, updated_at
FROM device_params
WHERE dongle_id = $1 AND key = $2
`

type GetDeviceParamParams struct {
	DongleID string `json:"dongleId"`
	Key      string `json:"key"`
}

func (q *Queries) GetDeviceParam(ctx context.Context, arg GetDeviceParamParams) (DeviceParam, error) {
	row := q.db.QueryRow(ctx, getDeviceParam, arg.DongleID, arg.Key)
	var i DeviceParam
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeviceParams = `-- name: ListDeviceParams :many
SELECT id, dongle_id, key, value, updated_at
FROM device_params
WHERE dongle_id = $1
ORDER BY key ASC
`

func (q *Queries) ListDeviceParams(ctx context.Context, dongleID string) ([]DeviceParam, error) {
	rows, err := q.db.Query(ctx, listDeviceParams, dongleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceParam
	for rows.Next() {
		var i DeviceParam
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeviceParam = `-- name: SetDeviceParam :one
INSERT INTO device_params (dongle_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (dongle_id, key) DO UPDATE SET value = $3, updated_at = now()
RETURNING id, dongle_id, key, value, updated_at
`

type SetDeviceParamParams struct {
	DongleID string `json:"dongleId"`
	Key      string `json:"key"`
	Value    string `json:"value"`
}

func (q *Queries) SetDeviceParam(ctx context.Context, arg SetDeviceParamParams) (DeviceParam, error) {
	row := q.db.QueryRow(ctx, setDeviceParam, arg.DongleID, arg.Key, arg.Value)
	var i DeviceParam
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.Key,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}
