// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (dongle_id, serial, public_key)
VALUES ($1, $2, $3)
RETURNING dongle_id, serial, public_key, created_at, updated_at
`

type CreateDeviceParams struct {
	DongleID  string      `json:"dongleId"`
	Serial    pgtype.Text `json:"serial"`
	PublicKey pgtype.Text `json:"publicKey"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.DongleID, arg.Serial, arg.PublicKey)
	var i Device
	err := row.Scan(
		&i.DongleID,
		&i.Serial,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT dongle_id, serial, public_key, created_at, updated_at
FROM devices
WHERE dongle_id = $1
`

func (q *Queries) GetDevice(ctx context.Context, dongleID string) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, dongleID)
	var i Device
	err := row.Scan(
		&i.DongleID,
		&i.Serial,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceByPublicKey = `-- name: GetDeviceByPublicKey :one
SELECT dongle_id, serial, public_key, created_at, updated_at
FROM devices
WHERE public_key = $1
LIMIT 1
`

func (q *Queries) GetDeviceByPublicKey(ctx context.Context, publicKey pgtype.Text) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByPublicKey, publicKey)
	var i Device
	err := row.Scan(
		&i.DongleID,
		&i.Serial,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT dongle_id, serial, public_key, created_at, updated_at
FROM devices
ORDER BY created_at DESC
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.DongleID,
			&i.Serial,
			&i.PublicKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO devices (dongle_id, serial, public_key)
VALUES ($1, $2, $3)
ON CONFLICT (dongle_id) DO UPDATE SET serial = $2, public_key = $3, updated_at = now()
RETURNING dongle_id, serial, public_key, created_at, updated_at
`

type UpsertDeviceParams struct {
	DongleID  string      `json:"dongleId"`
	Serial    pgtype.Text `json:"serial"`
	PublicKey pgtype.Text `json:"publicKey"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice, arg.DongleID, arg.Serial, arg.PublicKey)
	var i Device
	err := row.Scan(
		&i.DongleID,
		&i.Serial,
		&i.PublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
