// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByDongleID = `-- name: CountEventsByDongleID :one
SELECT COUNT(*)::BIGINT
FROM events e
JOIN routes r ON r.id = e.route_id
WHERE r.dongle_id = $1
  AND ($2::text IS NULL OR e.type = $2)
  AND ($3::text IS NULL OR e.severity = $3)
`

type CountEventsByDongleIDParams struct {
	DongleID       string      `json:"dongleId"`
	TypeFilter     pgtype.Text `json:"typeFilter"`
	SeverityFilter pgtype.Text `json:"severityFilter"`
}

// Total count matching the same filters as ListEventsByDongleID, so the UI
// can paginate without repeatedly scanning the full set. Pass NULL for
// @type_filter or @severity_filter to disable that filter.
func (q *Queries) CountEventsByDongleID(ctx context.Context, arg CountEventsByDongleIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByDongleID, arg.DongleID, arg.TypeFilter, arg.SeverityFilter)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countEventsByType = `-- name: CountEventsByType :many
SELECT type, count(*) AS count
FROM events
WHERE route_id = $1
GROUP BY type
ORDER BY count DESC, type ASC
`

type CountEventsByTypeRow struct {
	Type  string `json:"type"`
	Count int64  `json:"count"`
}

// Aggregate count of events grouped by type for a single route.
func (q *Queries) CountEventsByType(ctx context.Context, routeID int32) ([]CountEventsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countEventsByType, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountEventsByTypeRow
	for rows.Next() {
		var i CountEventsByTypeRow
		if err := rows.Scan(&i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    route_id,
    type,
    severity,
    route_offset_seconds,
    occurred_at,
    payload
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (route_id, type, route_offset_seconds) DO NOTHING
RETURNING id, route_id, type, severity, route_offset_seconds,
          occurred_at, payload, created_at
`

type InsertEventParams struct {
	RouteID            int32              `json:"routeId"`
	Type               string             `json:"type"`
	Severity           string             `json:"severity"`
	RouteOffsetSeconds float64            `json:"routeOffsetSeconds"`
	OccurredAt         pgtype.Timestamptz `json:"occurredAt"`
	Payload            []byte             `json:"payload"`
}

// Insert a new event. Reruns of a detector over the same (route, type, offset)
// are idempotent: the UNIQUE constraint causes the conflict to be skipped and
// nothing is returned. Callers should treat pgx.ErrNoRows as "already exists".
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.RouteID,
		arg.Type,
		arg.Severity,
		arg.RouteOffsetSeconds,
		arg.OccurredAt,
		arg.Payload,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Type,
		&i.Severity,
		&i.RouteOffsetSeconds,
		&i.OccurredAt,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByDongleID = `-- name: ListEventsByDongleID :many
SELECT e.id, e.route_id, e.type, e.severity, e.route_offset_seconds,
       e.occurred_at, e.payload, e.created_at,
       r.route_name, r.dongle_id
FROM events e
JOIN routes r ON r.id = e.route_id
WHERE r.dongle_id = $1
  AND ($2::text IS NULL OR e.type = $2)
  AND ($3::text IS NULL OR e.severity = $3)
ORDER BY e.occurred_at DESC NULLS LAST, e.id DESC
LIMIT $5 OFFSET $4
`

type ListEventsByDongleIDParams struct {
	DongleID       string      `json:"dongleId"`
	TypeFilter     pgtype.Text `json:"typeFilter"`
	SeverityFilter pgtype.Text `json:"severityFilter"`
	OffsetCount    int32       `json:"offsetCount"`
	LimitCount     int32       `json:"limitCount"`
}

type ListEventsByDongleIDRow struct {
	ID                 int32              `json:"id"`
	RouteID            int32              `json:"routeId"`
	Type               string             `json:"type"`
	Severity           string             `json:"severity"`
	RouteOffsetSeconds float64            `json:"routeOffsetSeconds"`
	OccurredAt         pgtype.Timestamptz `json:"occurredAt"`
	Payload            []byte             `json:"payload"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	RouteName          string             `json:"routeName"`
	DongleID           string             `json:"dongleId"`
}

// Paginated, filterable list of events for a device, joined with the owning
// route so the UI can render the route_name alongside the event without a
// second round trip. Pass NULL for @type_filter or @severity_filter to
// disable that filter.
func (q *Queries) ListEventsByDongleID(ctx context.Context, arg ListEventsByDongleIDParams) ([]ListEventsByDongleIDRow, error) {
	rows, err := q.db.Query(ctx, listEventsByDongleID,
		arg.DongleID,
		arg.TypeFilter,
		arg.SeverityFilter,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsByDongleIDRow
	for rows.Next() {
		var i ListEventsByDongleIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.Type,
			&i.Severity,
			&i.RouteOffsetSeconds,
			&i.OccurredAt,
			&i.Payload,
			&i.CreatedAt,
			&i.RouteName,
			&i.DongleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByRoute = `-- name: ListEventsByRoute :many
SELECT id, route_id, type, severity, route_offset_seconds,
       occurred_at, payload, created_at
FROM events
WHERE route_id = $1
ORDER BY route_offset_seconds ASC, id ASC
`

func (q *Queries) ListEventsByRoute(ctx context.Context, routeID int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.Type,
			&i.Severity,
			&i.RouteOffsetSeconds,
			&i.OccurredAt,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
