// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	DongleID  string             `json:"dongleId"`
	Serial    pgtype.Text        `json:"serial"`
	PublicKey pgtype.Text        `json:"publicKey"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type DeviceParam struct {
	ID        int32              `json:"id"`
	DongleID  string             `json:"dongleId"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Route struct {
	ID        int32              `json:"id"`
	DongleID  string             `json:"dongleId"`
	RouteName string             `json:"routeName"`
	StartTime pgtype.Timestamptz `json:"startTime"`
	EndTime   pgtype.Timestamptz `json:"endTime"`
	Geometry  interface{}        `json:"geometry"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Preserved bool               `json:"preserved"`
}

type Segment struct {
	ID              int32              `json:"id"`
	RouteID         int32              `json:"routeId"`
	SegmentNumber   int32              `json:"segmentNumber"`
	RlogUploaded    bool               `json:"rlogUploaded"`
	QlogUploaded    bool               `json:"qlogUploaded"`
	FcameraUploaded bool               `json:"fcameraUploaded"`
	EcameraUploaded bool               `json:"ecameraUploaded"`
	DcameraUploaded bool               `json:"dcameraUploaded"`
	QcameraUploaded bool               `json:"qcameraUploaded"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}
