// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Device struct {
	DongleID  string             `json:"dongleId"`
	Serial    pgtype.Text        `json:"serial"`
	PublicKey pgtype.Text        `json:"publicKey"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type DeviceParam struct {
	ID        int32              `json:"id"`
	DongleID  string             `json:"dongleId"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Route struct {
	ID        int32              `json:"id"`
	DongleID  string             `json:"dongleId"`
	RouteName string             `json:"routeName"`
	StartTime pgtype.Timestamptz `json:"startTime"`
	EndTime   pgtype.Timestamptz `json:"endTime"`
	Geometry  interface{}        `json:"geometry"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type Segment struct {
	ID              int32              `json:"id"`
	RouteID         int32              `json:"routeId"`
	SegmentNumber   int32              `json:"segmentNumber"`
	RlogUploaded    bool               `json:"rlogUploaded"`
	QlogUploaded    bool               `json:"qlogUploaded"`
	FcameraUploaded bool               `json:"fcameraUploaded"`
	EcameraUploaded bool               `json:"ecameraUploaded"`
	DcameraUploaded bool               `json:"dcameraUploaded"`
	QcameraUploaded bool               `json:"qcameraUploaded"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type Trip struct {
	ID              int32              `json:"id"`
	RouteID         int32              `json:"routeId"`
	DistanceMeters  pgtype.Float8      `json:"distanceMeters"`
	DurationSeconds pgtype.Int4        `json:"durationSeconds"`
	MaxSpeedMps     pgtype.Float8      `json:"maxSpeedMps"`
	AvgSpeedMps     pgtype.Float8      `json:"avgSpeedMps"`
	EngagedSeconds  pgtype.Int4        `json:"engagedSeconds"`
	StartAddress    pgtype.Text        `json:"startAddress"`
	EndAddress      pgtype.Text        `json:"endAddress"`
	StartLat        pgtype.Float8      `json:"startLat"`
	StartLng        pgtype.Float8      `json:"startLng"`
	EndLat          pgtype.Float8      `json:"endLat"`
	EndLng          pgtype.Float8      `json:"endLng"`
	ComputedAt      pgtype.Timestamptz `json:"computedAt"`
}
