// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlprAuditLog struct {
	ID        int64              `json:"id"`
	Action    string             `json:"action"`
	Actor     pgtype.Text        `json:"actor"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type AlprSegmentProgress struct {
	DongleID             string             `json:"dongleId"`
	Route                string             `json:"route"`
	Segment              int32              `json:"segment"`
	ProcessedAtExtractor pgtype.Timestamptz `json:"processedAtExtractor"`
	ProcessedAtDetector  pgtype.Timestamptz `json:"processedAtDetector"`
}

type Crash struct {
	ID          int32              `json:"id"`
	EventID     string             `json:"eventId"`
	DongleID    pgtype.Text        `json:"dongleId"`
	Level       string             `json:"level"`
	Message     string             `json:"message"`
	Fingerprint []byte             `json:"fingerprint"`
	Tags        []byte             `json:"tags"`
	Exception   []byte             `json:"exception"`
	Breadcrumbs []byte             `json:"breadcrumbs"`
	RawEvent    []byte             `json:"rawEvent"`
	OccurredAt  pgtype.Timestamptz `json:"occurredAt"`
	ReceivedAt  pgtype.Timestamptz `json:"receivedAt"`
}

type Device struct {
	DongleID           string             `json:"dongleId"`
	Serial             pgtype.Text        `json:"serial"`
	PublicKey          pgtype.Text        `json:"publicKey"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
	SunnylinkDongleID  pgtype.Text        `json:"sunnylinkDongleId"`
	SunnylinkPublicKey pgtype.Text        `json:"sunnylinkPublicKey"`
}

type DeviceParam struct {
	ID        int32              `json:"id"`
	DongleID  string             `json:"dongleId"`
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Event struct {
	ID                 int32              `json:"id"`
	RouteID            int32              `json:"routeId"`
	Type               string             `json:"type"`
	Severity           string             `json:"severity"`
	RouteOffsetSeconds float64            `json:"routeOffsetSeconds"`
	OccurredAt         pgtype.Timestamptz `json:"occurredAt"`
	Payload            []byte             `json:"payload"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
}

type PlateAlertEvent struct {
	ID               int64              `json:"id"`
	PlateHash        []byte             `json:"plateHash"`
	Route            pgtype.Text        `json:"route"`
	DongleID         pgtype.Text        `json:"dongleId"`
	ComputedAt       pgtype.Timestamptz `json:"computedAt"`
	Severity         int16              `json:"severity"`
	Components       []byte             `json:"components"`
	HeuristicVersion string             `json:"heuristicVersion"`
}

type PlateDetection struct {
	ID                int64              `json:"id"`
	DongleID          string             `json:"dongleId"`
	Route             string             `json:"route"`
	Segment           int32              `json:"segment"`
	FrameOffsetMs     int32              `json:"frameOffsetMs"`
	PlateCiphertext   []byte             `json:"plateCiphertext"`
	PlateHash         []byte             `json:"plateHash"`
	Bbox              []byte             `json:"bbox"`
	Confidence        float32            `json:"confidence"`
	OcrCorrected      bool               `json:"ocrCorrected"`
	GpsLat            pgtype.Float8      `json:"gpsLat"`
	GpsLng            pgtype.Float8      `json:"gpsLng"`
	GpsHeadingDeg     pgtype.Float4      `json:"gpsHeadingDeg"`
	FrameTs           pgtype.Timestamptz `json:"frameTs"`
	ThumbPath         pgtype.Text        `json:"thumbPath"`
	CreatedAt         pgtype.Timestamptz `json:"createdAt"`
	SignatureID       pgtype.Int8        `json:"signatureId"`
	DetMake           pgtype.Text        `json:"detMake"`
	DetModel          pgtype.Text        `json:"detModel"`
	DetColor          pgtype.Text        `json:"detColor"`
	DetBodyType       pgtype.Text        `json:"detBodyType"`
	DetAttrConfidence pgtype.Float4      `json:"detAttrConfidence"`
}

type PlateEncounter struct {
	ID                    int64              `json:"id"`
	DongleID              string             `json:"dongleId"`
	Route                 string             `json:"route"`
	PlateHash             []byte             `json:"plateHash"`
	FirstSeenTs           pgtype.Timestamptz `json:"firstSeenTs"`
	LastSeenTs            pgtype.Timestamptz `json:"lastSeenTs"`
	DetectionCount        int32              `json:"detectionCount"`
	TurnCount             int32              `json:"turnCount"`
	MaxInternalGapSeconds int32              `json:"maxInternalGapSeconds"`
	SignatureID           pgtype.Int8        `json:"signatureId"`
	Status                string             `json:"status"`
	BboxFirst             []byte             `json:"bboxFirst"`
	BboxLast              []byte             `json:"bboxLast"`
	CreatedAt             pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt             pgtype.Timestamptz `json:"updatedAt"`
}

type PlateWatchlist struct {
	ID              int64              `json:"id"`
	PlateHash       []byte             `json:"plateHash"`
	LabelCiphertext []byte             `json:"labelCiphertext"`
	Kind            string             `json:"kind"`
	Severity        pgtype.Int2        `json:"severity"`
	FirstAlertAt    pgtype.Timestamptz `json:"firstAlertAt"`
	LastAlertAt     pgtype.Timestamptz `json:"lastAlertAt"`
	AckedAt         pgtype.Timestamptz `json:"ackedAt"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	SignatureID     pgtype.Int8        `json:"signatureId"`
}

type Route struct {
	ID        int32              `json:"id"`
	DongleID  string             `json:"dongleId"`
	RouteName string             `json:"routeName"`
	StartTime pgtype.Timestamptz `json:"startTime"`
	EndTime   pgtype.Timestamptz `json:"endTime"`
	Geometry  interface{}        `json:"geometry"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Preserved bool               `json:"preserved"`
	Note      string             `json:"note"`
	Starred   bool               `json:"starred"`
	// Route-relative milliseconds for each vertex of routes.geometry, parallel array (length matches ST_NumPoints(geometry)). NULL for routes whose metadata predates the column; backfilled by the route metadata worker on its next pass.
	GeometryTimes []int64 `json:"geometryTimes"`
}

type RouteDataRequest struct {
	ID             int32              `json:"id"`
	RouteID        int32              `json:"routeId"`
	RequestedBy    pgtype.Text        `json:"requestedBy"`
	RequestedAt    pgtype.Timestamptz `json:"requestedAt"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	DispatchedAt   pgtype.Timestamptz `json:"dispatchedAt"`
	CompletedAt    pgtype.Timestamptz `json:"completedAt"`
	Error          pgtype.Text        `json:"error"`
	FilesRequested int32              `json:"filesRequested"`
}

type RouteTag struct {
	RouteID int32  `json:"routeId"`
	Tag     string `json:"tag"`
}

type RouteTurn struct {
	ID               int64              `json:"id"`
	DongleID         string             `json:"dongleId"`
	Route            string             `json:"route"`
	TurnTs           pgtype.Timestamptz `json:"turnTs"`
	TurnOffsetMs     int32              `json:"turnOffsetMs"`
	BearingBeforeDeg float32            `json:"bearingBeforeDeg"`
	BearingAfterDeg  float32            `json:"bearingAfterDeg"`
	DeltaDeg         float32            `json:"deltaDeg"`
	GpsLat           pgtype.Float8      `json:"gpsLat"`
	GpsLng           pgtype.Float8      `json:"gpsLng"`
}

type Segment struct {
	ID              int32              `json:"id"`
	RouteID         int32              `json:"routeId"`
	SegmentNumber   int32              `json:"segmentNumber"`
	RlogUploaded    bool               `json:"rlogUploaded"`
	QlogUploaded    bool               `json:"qlogUploaded"`
	FcameraUploaded bool               `json:"fcameraUploaded"`
	EcameraUploaded bool               `json:"ecameraUploaded"`
	DcameraUploaded bool               `json:"dcameraUploaded"`
	QcameraUploaded bool               `json:"qcameraUploaded"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type Setting struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type Trip struct {
	ID               int32              `json:"id"`
	RouteID          int32              `json:"routeId"`
	DistanceMeters   pgtype.Float8      `json:"distanceMeters"`
	DurationSeconds  pgtype.Int4        `json:"durationSeconds"`
	MaxSpeedMps      pgtype.Float8      `json:"maxSpeedMps"`
	AvgSpeedMps      pgtype.Float8      `json:"avgSpeedMps"`
	EngagedSeconds   pgtype.Int4        `json:"engagedSeconds"`
	StartAddress     pgtype.Text        `json:"startAddress"`
	EndAddress       pgtype.Text        `json:"endAddress"`
	StartLat         pgtype.Float8      `json:"startLat"`
	StartLng         pgtype.Float8      `json:"startLng"`
	EndLat           pgtype.Float8      `json:"endLat"`
	EndLng           pgtype.Float8      `json:"endLng"`
	ComputedAt       pgtype.Timestamptz `json:"computedAt"`
	EventsComputedAt pgtype.Timestamptz `json:"eventsComputedAt"`
}

type UiUser struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"passwordHash"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type VehicleSignature struct {
	ID           int64              `json:"id"`
	SignatureKey string             `json:"signatureKey"`
	Make         pgtype.Text        `json:"make"`
	Model        pgtype.Text        `json:"model"`
	YearMin      pgtype.Int4        `json:"yearMin"`
	YearMax      pgtype.Int4        `json:"yearMax"`
	Color        pgtype.Text        `json:"color"`
	BodyType     pgtype.Text        `json:"bodyType"`
	Confidence   pgtype.Float4      `json:"confidence"`
	SampleCount  int32              `json:"sampleCount"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
}
