// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route_data_requests.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRouteDataRequest = `-- name: CreateRouteDataRequest :one
INSERT INTO route_data_requests (
    route_id, requested_by, kind, status, files_requested,
    dispatched_at, error
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, route_id, requested_by, requested_at, kind, status,
          dispatched_at, completed_at, error, files_requested
`

type CreateRouteDataRequestParams struct {
	RouteID        int32              `json:"routeId"`
	RequestedBy    pgtype.Text        `json:"requestedBy"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	FilesRequested int32              `json:"filesRequested"`
	DispatchedAt   pgtype.Timestamptz `json:"dispatchedAt"`
	Error          pgtype.Text        `json:"error"`
}

// Inserts a fresh request row. status defaults to 'pending'; the caller
// transitions it to 'dispatched' (or 'failed') after attempting the RPC.
func (q *Queries) CreateRouteDataRequest(ctx context.Context, arg CreateRouteDataRequestParams) (RouteDataRequest, error) {
	row := q.db.QueryRow(ctx, createRouteDataRequest,
		arg.RouteID,
		arg.RequestedBy,
		arg.Kind,
		arg.Status,
		arg.FilesRequested,
		arg.DispatchedAt,
		arg.Error,
	)
	var i RouteDataRequest
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Kind,
		&i.Status,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.Error,
		&i.FilesRequested,
	)
	return i, err
}

const getLatestRouteDataRequestByRoute = `-- name: GetLatestRouteDataRequestByRoute :one
SELECT id, route_id, requested_by, requested_at, kind, status,
       dispatched_at, completed_at, error, files_requested
FROM route_data_requests
WHERE route_id = $1 AND kind = $2
ORDER BY requested_at DESC
LIMIT 1
`

type GetLatestRouteDataRequestByRouteParams struct {
	RouteID int32  `json:"routeId"`
	Kind    string `json:"kind"`
}

// Returns the most recent request for a route+kind. Used by the POST handler
// to short-circuit duplicate dispatches within the idempotency window, and by
// the polling UI to surface the current state without knowing the request id.
func (q *Queries) GetLatestRouteDataRequestByRoute(ctx context.Context, arg GetLatestRouteDataRequestByRouteParams) (RouteDataRequest, error) {
	row := q.db.QueryRow(ctx, getLatestRouteDataRequestByRoute, arg.RouteID, arg.Kind)
	var i RouteDataRequest
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Kind,
		&i.Status,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.Error,
		&i.FilesRequested,
	)
	return i, err
}

const getRouteDataRequestByID = `-- name: GetRouteDataRequestByID :one
SELECT id, route_id, requested_by, requested_at, kind, status,
       dispatched_at, completed_at, error, files_requested
FROM route_data_requests
WHERE id = $1
`

func (q *Queries) GetRouteDataRequestByID(ctx context.Context, id int32) (RouteDataRequest, error) {
	row := q.db.QueryRow(ctx, getRouteDataRequestByID, id)
	var i RouteDataRequest
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.Kind,
		&i.Status,
		&i.DispatchedAt,
		&i.CompletedAt,
		&i.Error,
		&i.FilesRequested,
	)
	return i, err
}

const listPendingRouteDataRequests = `-- name: ListPendingRouteDataRequests :many
SELECT r.id          AS request_id,
       r.route_id    AS route_id,
       r.requested_by,
       r.requested_at,
       r.kind        AS kind,
       r.status      AS status,
       r.files_requested,
       rt.dongle_id  AS dongle_id,
       rt.route_name AS route_name
FROM route_data_requests r
JOIN routes rt ON rt.id = r.route_id
WHERE r.status = 'pending'
ORDER BY r.requested_at ASC
LIMIT $1
`

type ListPendingRouteDataRequestsRow struct {
	RequestID      int32              `json:"requestId"`
	RouteID        int32              `json:"routeId"`
	RequestedBy    pgtype.Text        `json:"requestedBy"`
	RequestedAt    pgtype.Timestamptz `json:"requestedAt"`
	Kind           string             `json:"kind"`
	Status         string             `json:"status"`
	FilesRequested int32              `json:"filesRequested"`
	DongleID       string             `json:"dongleId"`
	RouteName      string             `json:"routeName"`
}

// Returns pending rows that the dispatcher worker should retry. Joined with
// routes so the worker has the dongle id needed to look the device up on the
// WebSocket hub without a second query per row.
func (q *Queries) ListPendingRouteDataRequests(ctx context.Context, limit int32) ([]ListPendingRouteDataRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRouteDataRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRouteDataRequestsRow
	for rows.Next() {
		var i ListPendingRouteDataRequestsRow
		if err := rows.Scan(
			&i.RequestID,
			&i.RouteID,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.Kind,
			&i.Status,
			&i.FilesRequested,
			&i.DongleID,
			&i.RouteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRouteDataRequestStatus = `-- name: UpdateRouteDataRequestStatus :exec
UPDATE route_data_requests
SET status        = $1,
    dispatched_at = COALESCE($2::timestamptz, dispatched_at),
    completed_at  = COALESCE($3::timestamptz, completed_at),
    error         = COALESCE($4::text, error)
WHERE id = $5
`

type UpdateRouteDataRequestStatusParams struct {
	Status       string             `json:"status"`
	DispatchedAt pgtype.Timestamptz `json:"dispatchedAt"`
	CompletedAt  pgtype.Timestamptz `json:"completedAt"`
	Error        pgtype.Text        `json:"error"`
	ID           int32              `json:"id"`
}

// Updates status (and the appropriate timestamp/error fields) on an existing
// row. NULL inputs leave the corresponding column untouched so partial
// progress updates do not stomp prior data.
func (q *Queries) UpdateRouteDataRequestStatus(ctx context.Context, arg UpdateRouteDataRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateRouteDataRequestStatus,
		arg.Status,
		arg.DispatchedAt,
		arg.CompletedAt,
		arg.Error,
		arg.ID,
	)
	return err
}
