// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoutesByDevice = `-- name: CountRoutesByDevice :one
SELECT count(*) FROM routes WHERE dongle_id = $1
`

func (q *Queries) CountRoutesByDevice(ctx context.Context, dongleID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutesByDevice, dongleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (dongle_id, route_name, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
`

type CreateRouteParams struct {
	DongleID  string             `json:"dongleId"`
	RouteName string             `json:"routeName"`
	StartTime pgtype.Timestamptz `json:"startTime"`
	EndTime   pgtype.Timestamptz `json:"endTime"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.DongleID,
		arg.RouteName,
		arg.StartTime,
		arg.EndTime,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
		&i.Note,
		&i.Starred,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes
WHERE id = $1
`

// Deletes a route row. Segments and trips reference it with ON DELETE CASCADE
// so they are removed automatically.
func (q *Queries) DeleteRoute(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
FROM routes
WHERE dongle_id = $1 AND route_name = $2
`

type GetRouteParams struct {
	DongleID  string `json:"dongleId"`
	RouteName string `json:"routeName"`
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, arg.DongleID, arg.RouteName)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
		&i.Note,
		&i.Starred,
	)
	return i, err
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
FROM routes
WHERE id = $1
`

func (q *Queries) GetRouteByID(ctx context.Context, id int32) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByID, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
		&i.Note,
		&i.Starred,
	)
	return i, err
}

const listPreservedRoutes = `-- name: ListPreservedRoutes :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
FROM routes
WHERE preserved = true
ORDER BY created_at DESC
`

func (q *Queries) ListPreservedRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, listPreservedRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
			&i.Note,
			&i.Starred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByDevice = `-- name: ListRoutesByDevice :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
FROM routes
WHERE dongle_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRoutesByDevice(ctx context.Context, dongleID string) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByDevice, dongleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
			&i.Note,
			&i.Starred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByDevicePaginated = `-- name: ListRoutesByDevicePaginated :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
FROM routes
WHERE dongle_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListRoutesByDevicePaginatedParams struct {
	DongleID string `json:"dongleId"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListRoutesByDevicePaginated(ctx context.Context, arg ListRoutesByDevicePaginatedParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByDevicePaginated, arg.DongleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
			&i.Note,
			&i.Starred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRoutes = `-- name: ListStaleRoutes :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
FROM routes
WHERE preserved = false
  AND end_time IS NOT NULL
  AND end_time < $1
ORDER BY end_time ASC
LIMIT $2
`

type ListStaleRoutesParams struct {
	EndTime pgtype.Timestamptz `json:"endTime"`
	Limit   int32              `json:"limit"`
}

// Returns non-preserved routes whose end_time is older than the given cutoff.
// Used by the cleanup worker; ordered by end_time asc so the oldest routes are
// deleted first when MaxDeletionsPerRun caps the batch.
func (q *Queries) ListStaleRoutes(ctx context.Context, arg ListStaleRoutesParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listStaleRoutes, arg.EndTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
			&i.Note,
			&i.Starred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRouteNote = `-- name: SetRouteNote :one
UPDATE routes
SET note = $2
WHERE id = $1
RETURNING id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
`

type SetRouteNoteParams struct {
	ID   int32  `json:"id"`
	Note string `json:"note"`
}

// Updates the free-form note on a route, keyed by the route's numeric id.
func (q *Queries) SetRouteNote(ctx context.Context, arg SetRouteNoteParams) (Route, error) {
	row := q.db.QueryRow(ctx, setRouteNote, arg.ID, arg.Note)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
		&i.Note,
		&i.Starred,
	)
	return i, err
}

const setRoutePreserved = `-- name: SetRoutePreserved :one
UPDATE routes
SET preserved = $3
WHERE dongle_id = $1 AND route_name = $2
RETURNING id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
`

type SetRoutePreservedParams struct {
	DongleID  string `json:"dongleId"`
	RouteName string `json:"routeName"`
	Preserved bool   `json:"preserved"`
}

func (q *Queries) SetRoutePreserved(ctx context.Context, arg SetRoutePreservedParams) (Route, error) {
	row := q.db.QueryRow(ctx, setRoutePreserved, arg.DongleID, arg.RouteName, arg.Preserved)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
		&i.Note,
		&i.Starred,
	)
	return i, err
}

const setRouteStarred = `-- name: SetRouteStarred :one
UPDATE routes
SET starred = $2
WHERE id = $1
RETURNING id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved, note, starred
`

type SetRouteStarredParams struct {
	ID      int32 `json:"id"`
	Starred bool  `json:"starred"`
}

// Toggles the starred/favorite flag on a route, keyed by the route's numeric id.
func (q *Queries) SetRouteStarred(ctx context.Context, arg SetRouteStarredParams) (Route, error) {
	row := q.db.QueryRow(ctx, setRouteStarred, arg.ID, arg.Starred)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
		&i.Note,
		&i.Starred,
	)
	return i, err
}
