// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route_tags.sql

package db

import (
	"context"
)

const addRouteTag = `-- name: AddRouteTag :exec
INSERT INTO route_tags (route_id, tag)
VALUES ($1, $2)
ON CONFLICT (route_id, tag) DO NOTHING
`

type AddRouteTagParams struct {
	RouteID int32  `json:"routeId"`
	Tag     string `json:"tag"`
}

// Adds a single tag to a route. Idempotent: the PRIMARY KEY (route_id, tag)
// plus ON CONFLICT DO NOTHING means re-adding an existing tag is a no-op.
func (q *Queries) AddRouteTag(ctx context.Context, arg AddRouteTagParams) error {
	_, err := q.db.Exec(ctx, addRouteTag, arg.RouteID, arg.Tag)
	return err
}

const listTagsForDevice = `-- name: ListTagsForDevice :many
SELECT DISTINCT rt.tag
FROM route_tags rt
JOIN routes r ON r.id = rt.route_id
WHERE r.dongle_id = $1
ORDER BY rt.tag ASC
`

// Returns the distinct set of tags that exist across all of a device's routes,
// alphabetically sorted. Backs the tag-picker/autocomplete in the UI.
func (q *Queries) ListTagsForDevice(ctx context.Context, dongleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listTagsForDevice, dongleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForRoute = `-- name: ListTagsForRoute :many
SELECT tag
FROM route_tags
WHERE route_id = $1
ORDER BY tag ASC
`

// Returns the tags attached to a route in stable alphabetical order.
func (q *Queries) ListTagsForRoute(ctx context.Context, routeID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listTagsForRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRouteTag = `-- name: RemoveRouteTag :exec
DELETE FROM route_tags
WHERE route_id = $1 AND tag = $2
`

type RemoveRouteTagParams struct {
	RouteID int32  `json:"routeId"`
	Tag     string `json:"tag"`
}

func (q *Queries) RemoveRouteTag(ctx context.Context, arg RemoveRouteTagParams) error {
	_, err := q.db.Exec(ctx, removeRouteTag, arg.RouteID, arg.Tag)
	return err
}

const replaceRouteTagsDelete = `-- name: ReplaceRouteTagsDelete :exec
DELETE FROM route_tags
WHERE route_id = $1
`

// First half of ReplaceRouteTags: clears the existing tag set for a route.
// Callers must run this inside the same transaction as the subsequent
// AddRouteTag inserts; the Go wrapper ReplaceRouteTags handles that.
func (q *Queries) ReplaceRouteTagsDelete(ctx context.Context, routeID int32) error {
	_, err := q.db.Exec(ctx, replaceRouteTagsDelete, routeID)
	return err
}
