// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoutesByDevice = `-- name: CountRoutesByDevice :one
SELECT count(*) FROM routes WHERE dongle_id = $1
`

func (q *Queries) CountRoutesByDevice(ctx context.Context, dongleID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutesByDevice, dongleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRoutesByDeviceFiltered = `-- name: CountRoutesByDeviceFiltered :one
SELECT COUNT(*)::BIGINT
FROM routes r
LEFT JOIN trips t ON t.route_id = r.id
WHERE r.dongle_id = $1
  AND ($2::timestamptz IS NULL
       OR r.start_time >= $2::timestamptz)
  AND ($3::timestamptz IS NULL
       OR r.start_time <  $3::timestamptz)
  AND ($4::bool IS NULL
       OR r.preserved = $4::bool)
  AND ($5::int IS NULL
       OR (t.duration_seconds IS NOT NULL
           AND t.duration_seconds >= $5::int))
  AND ($6::int IS NULL
       OR (t.duration_seconds IS NOT NULL
           AND t.duration_seconds <= $6::int))
  AND ($7::double precision IS NULL
       OR (t.distance_meters IS NOT NULL
           AND t.distance_meters >= $7::double precision))
  AND ($8::double precision IS NULL
       OR (t.distance_meters IS NOT NULL
           AND t.distance_meters <= $8::double precision))
  AND ($9::bool IS NULL
       OR ($9::bool = TRUE
           AND EXISTS (SELECT 1 FROM events e WHERE e.route_id = r.id))
       OR ($9::bool = FALSE
           AND NOT EXISTS (SELECT 1 FROM events e WHERE e.route_id = r.id)))
`

type CountRoutesByDeviceFilteredParams struct {
	DongleID     string             `json:"dongleId"`
	FromTime     pgtype.Timestamptz `json:"fromTime"`
	ToTime       pgtype.Timestamptz `json:"toTime"`
	Preserved    pgtype.Bool        `json:"preserved"`
	MinDurationS pgtype.Int4        `json:"minDurationS"`
	MaxDurationS pgtype.Int4        `json:"maxDurationS"`
	MinDistanceM pgtype.Float8      `json:"minDistanceM"`
	MaxDistanceM pgtype.Float8      `json:"maxDistanceM"`
	HasEvents    pgtype.Bool        `json:"hasEvents"`
}

// Returns the number of routes for a device matching the same filter set as
// the dashboard routes list. Pass NULL for any filter arg to disable it.
//
// Routes without an aggregated trip row are INCLUDED unless a duration or
// distance filter is set; with those filters they are excluded because there
// is no trip to compare against.
//
// has_events:
//
//	NULL  -> no filter
//	TRUE  -> only routes with at least one row in events
//	FALSE -> only routes with zero rows in events
//
// Uses an EXISTS subquery (not LEFT JOIN GROUP BY) so the planner can use
// the idx_events_route_id index.
func (q *Queries) CountRoutesByDeviceFiltered(ctx context.Context, arg CountRoutesByDeviceFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutesByDeviceFiltered,
		arg.DongleID,
		arg.FromTime,
		arg.ToTime,
		arg.Preserved,
		arg.MinDurationS,
		arg.MaxDurationS,
		arg.MinDistanceM,
		arg.MaxDistanceM,
		arg.HasEvents,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (dongle_id, route_name, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved
`

type CreateRouteParams struct {
	DongleID  string             `json:"dongleId"`
	RouteName string             `json:"routeName"`
	StartTime pgtype.Timestamptz `json:"startTime"`
	EndTime   pgtype.Timestamptz `json:"endTime"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.DongleID,
		arg.RouteName,
		arg.StartTime,
		arg.EndTime,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
	)
	return i, err
}

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes
WHERE id = $1
`

// Deletes a route row. Segments and trips reference it with ON DELETE CASCADE
// so they are removed automatically.
func (q *Queries) DeleteRoute(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRoute, id)
	return err
}

const getRoute = `-- name: GetRoute :one
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved
FROM routes
WHERE dongle_id = $1 AND route_name = $2
`

type GetRouteParams struct {
	DongleID  string `json:"dongleId"`
	RouteName string `json:"routeName"`
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, arg.DongleID, arg.RouteName)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
	)
	return i, err
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved
FROM routes
WHERE id = $1
`

func (q *Queries) GetRouteByID(ctx context.Context, id int32) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByID, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
	)
	return i, err
}

const listPreservedRoutes = `-- name: ListPreservedRoutes :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved
FROM routes
WHERE preserved = true
ORDER BY created_at DESC
`

func (q *Queries) ListPreservedRoutes(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, listPreservedRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByDevice = `-- name: ListRoutesByDevice :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved
FROM routes
WHERE dongle_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRoutesByDevice(ctx context.Context, dongleID string) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByDevice, dongleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByDevicePaginated = `-- name: ListRoutesByDevicePaginated :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved
FROM routes
WHERE dongle_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListRoutesByDevicePaginatedParams struct {
	DongleID string `json:"dongleId"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListRoutesByDevicePaginated(ctx context.Context, arg ListRoutesByDevicePaginatedParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByDevicePaginated, arg.DongleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRoutes = `-- name: ListStaleRoutes :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved
FROM routes
WHERE preserved = false
  AND end_time IS NOT NULL
  AND end_time < $1
ORDER BY end_time ASC
LIMIT $2
`

type ListStaleRoutesParams struct {
	EndTime pgtype.Timestamptz `json:"endTime"`
	Limit   int32              `json:"limit"`
}

// Returns non-preserved routes whose end_time is older than the given cutoff.
// Used by the cleanup worker; ordered by end_time asc so the oldest routes are
// deleted first when MaxDeletionsPerRun caps the batch.
func (q *Queries) ListStaleRoutes(ctx context.Context, arg ListStaleRoutesParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listStaleRoutes, arg.EndTime, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
			&i.Preserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoutePreserved = `-- name: SetRoutePreserved :one
UPDATE routes
SET preserved = $3
WHERE dongle_id = $1 AND route_name = $2
RETURNING id, dongle_id, route_name, start_time, end_time, geometry, created_at, preserved
`

type SetRoutePreservedParams struct {
	DongleID  string `json:"dongleId"`
	RouteName string `json:"routeName"`
	Preserved bool   `json:"preserved"`
}

func (q *Queries) SetRoutePreserved(ctx context.Context, arg SetRoutePreservedParams) (Route, error) {
	row := q.db.QueryRow(ctx, setRoutePreserved, arg.DongleID, arg.RouteName, arg.Preserved)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
		&i.Preserved,
	)
	return i, err
}
