// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route_turns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTurnsInWindow = `-- name: CountTurnsInWindow :one
SELECT COUNT(*)::BIGINT
FROM route_turns
WHERE dongle_id = $1
  AND route     = $2
  AND turn_ts  >= $3
  AND turn_ts  <= $4
`

type CountTurnsInWindowParams struct {
	DongleID    string             `json:"dongleId"`
	Route       string             `json:"route"`
	WindowStart pgtype.Timestamptz `json:"windowStart"`
	WindowEnd   pgtype.Timestamptz `json:"windowEnd"`
}

// Number of turns on a route that fall inside an inclusive time window.
// Backs the stalking heuristic's "did the suspect plate take the same
// N turns we did" check without forcing the heuristic to load every
// turn for every encounter.
func (q *Queries) CountTurnsInWindow(ctx context.Context, arg CountTurnsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTurnsInWindow,
		arg.DongleID,
		arg.Route,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteTurnsForRoute = `-- name: DeleteTurnsForRoute :execrows
DELETE FROM route_turns
WHERE dongle_id = $1 AND route = $2
`

type DeleteTurnsForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

// Wipe the route_turns rows for one route. The turn detector calls this
// before re-running over a route so the new pass starts from a clean
// slate. Returns the number of rows deleted.
func (q *Queries) DeleteTurnsForRoute(ctx context.Context, arg DeleteTurnsForRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTurnsForRoute, arg.DongleID, arg.Route)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertTurns = `-- name: InsertTurns :execrows
INSERT INTO route_turns (
    dongle_id,
    route,
    turn_ts,
    turn_offset_ms,
    bearing_before_deg,
    bearing_after_deg,
    delta_deg,
    gps_lat,
    gps_lng
)
SELECT $1::TEXT,
       $2::TEXT,
       ts.v,
       off.v,
       bb.v,
       ba.v,
       d.v,
       lat.v,
       lng.v
FROM UNNEST($3::TIMESTAMPTZ[])           WITH ORDINALITY AS ts(v, idx)
JOIN UNNEST($4::INT[])            WITH ORDINALITY AS off(v, idx) USING (idx)
JOIN UNNEST($5::REAL[])       WITH ORDINALITY AS bb(v, idx)  USING (idx)
JOIN UNNEST($6::REAL[])        WITH ORDINALITY AS ba(v, idx)  USING (idx)
JOIN UNNEST($7::REAL[])                WITH ORDINALITY AS d(v, idx)   USING (idx)
JOIN UNNEST($8::DOUBLE PRECISION[])      WITH ORDINALITY AS lat(v, idx) USING (idx)
JOIN UNNEST($9::DOUBLE PRECISION[])      WITH ORDINALITY AS lng(v, idx) USING (idx)
ON CONFLICT (dongle_id, route, turn_offset_ms) DO NOTHING
`

type InsertTurnsParams struct {
	DongleID         string               `json:"dongleId"`
	Route            string               `json:"route"`
	TurnTs           []pgtype.Timestamptz `json:"turnTs"`
	TurnOffsetMs     []int32              `json:"turnOffsetMs"`
	BearingBeforeDeg []float32            `json:"bearingBeforeDeg"`
	BearingAfterDeg  []float32            `json:"bearingAfterDeg"`
	DeltaDeg         []float32            `json:"deltaDeg"`
	GpsLat           []float64            `json:"gpsLat"`
	GpsLng           []float64            `json:"gpsLng"`
}

// Batch-insert detected turns for a route. Parallel arrays (one entry
// per turn) are joined together via WITH ORDINALITY so the i-th element
// of every array forms one row. ON CONFLICT DO NOTHING keeps
// reprocessing idempotent: a turn whose (dongle_id, route,
// turn_offset_ms) already exists is skipped. Callers should pair this
// with DeleteTurnsForRoute when they want a full overwrite. gps_lat
// and gps_lng are passed as arrays of DOUBLE PRECISION; SQL NULL
// elements are preserved through the join.
func (q *Queries) InsertTurns(ctx context.Context, arg InsertTurnsParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTurns,
		arg.DongleID,
		arg.Route,
		arg.TurnTs,
		arg.TurnOffsetMs,
		arg.BearingBeforeDeg,
		arg.BearingAfterDeg,
		arg.DeltaDeg,
		arg.GpsLat,
		arg.GpsLng,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTurnsForRoute = `-- name: ListTurnsForRoute :many
SELECT id, dongle_id, route, turn_ts, turn_offset_ms,
       bearing_before_deg, bearing_after_deg, delta_deg,
       gps_lat, gps_lng
FROM route_turns
WHERE dongle_id = $1 AND route = $2
ORDER BY turn_ts ASC, id ASC
`

type ListTurnsForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

// Time-ordered turn list for a single route. Used by the route overlay
// UI and by the stalking heuristic, which iterates turns to compare
// against per-encounter time windows.
func (q *Queries) ListTurnsForRoute(ctx context.Context, arg ListTurnsForRouteParams) ([]RouteTurn, error) {
	rows, err := q.db.Query(ctx, listTurnsForRoute, arg.DongleID, arg.Route)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteTurn
	for rows.Next() {
		var i RouteTurn
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.TurnTs,
			&i.TurnOffsetMs,
			&i.BearingBeforeDeg,
			&i.BearingAfterDeg,
			&i.DeltaDeg,
			&i.GpsLat,
			&i.GpsLng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
