// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: routes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRoutesByDevice = `-- name: CountRoutesByDevice :one
SELECT count(*) FROM routes WHERE dongle_id = $1
`

func (q *Queries) CountRoutesByDevice(ctx context.Context, dongleID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRoutesByDevice, dongleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRoute = `-- name: CreateRoute :one
INSERT INTO routes (dongle_id, route_name, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, dongle_id, route_name, start_time, end_time, geometry, created_at
`

type CreateRouteParams struct {
	DongleID  string             `json:"dongleId"`
	RouteName string             `json:"routeName"`
	StartTime pgtype.Timestamptz `json:"startTime"`
	EndTime   pgtype.Timestamptz `json:"endTime"`
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.DongleID,
		arg.RouteName,
		arg.StartTime,
		arg.EndTime,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at
FROM routes
WHERE dongle_id = $1 AND route_name = $2
`

type GetRouteParams struct {
	DongleID  string `json:"dongleId"`
	RouteName string `json:"routeName"`
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, arg.DongleID, arg.RouteName)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
	)
	return i, err
}

const getRouteByID = `-- name: GetRouteByID :one
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at
FROM routes
WHERE id = $1
`

func (q *Queries) GetRouteByID(ctx context.Context, id int32) (Route, error) {
	row := q.db.QueryRow(ctx, getRouteByID, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.DongleID,
		&i.RouteName,
		&i.StartTime,
		&i.EndTime,
		&i.Geometry,
		&i.CreatedAt,
	)
	return i, err
}

const listRoutesByDevice = `-- name: ListRoutesByDevice :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at
FROM routes
WHERE dongle_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRoutesByDevice(ctx context.Context, dongleID string) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByDevice, dongleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoutesByDevicePaginated = `-- name: ListRoutesByDevicePaginated :many
SELECT id, dongle_id, route_name, start_time, end_time, geometry, created_at
FROM routes
WHERE dongle_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListRoutesByDevicePaginatedParams struct {
	DongleID string `json:"dongleId"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListRoutesByDevicePaginated(ctx context.Context, arg ListRoutesByDevicePaginatedParams) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoutesByDevicePaginated, arg.DongleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
			&i.EndTime,
			&i.Geometry,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
