// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: route_turns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTurnsForRoute = `-- name: CountTurnsForRoute :one
SELECT COUNT(*) AS turn_count
FROM route_turns
WHERE dongle_id = $1 AND route = $2
`

type CountTurnsForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

func (q *Queries) CountTurnsForRoute(ctx context.Context, arg CountTurnsForRouteParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTurnsForRoute, arg.DongleID, arg.Route)
	var turn_count int64
	err := row.Scan(&turn_count)
	return turn_count, err
}

const countTurnsInWindow = `-- name: CountTurnsInWindow :one
SELECT COUNT(*) AS turn_count
FROM route_turns
WHERE dongle_id = $1
  AND route     = $2
  AND turn_ts  >= $3
  AND turn_ts  <= $4
`

type CountTurnsInWindowParams struct {
	DongleID string             `json:"dongleId"`
	Route    string             `json:"route"`
	TurnTs   pgtype.Timestamptz `json:"turnTs"`
	TurnTs_2 pgtype.Timestamptz `json:"turnTs2"`
}

func (q *Queries) CountTurnsInWindow(ctx context.Context, arg CountTurnsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTurnsInWindow,
		arg.DongleID,
		arg.Route,
		arg.TurnTs,
		arg.TurnTs_2,
	)
	var turn_count int64
	err := row.Scan(&turn_count)
	return turn_count, err
}

const deleteTurnsForRoute = `-- name: DeleteTurnsForRoute :exec
DELETE FROM route_turns
WHERE dongle_id = $1 AND route = $2
`

type DeleteTurnsForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

func (q *Queries) DeleteTurnsForRoute(ctx context.Context, arg DeleteTurnsForRouteParams) error {
	_, err := q.db.Exec(ctx, deleteTurnsForRoute, arg.DongleID, arg.Route)
	return err
}

const insertTurn = `-- name: InsertTurn :exec
INSERT INTO route_turns (
    dongle_id,
    route,
    turn_ts,
    turn_offset_ms,
    bearing_before_deg,
    bearing_after_deg,
    delta_deg,
    gps_lat,
    gps_lng
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (dongle_id, route, turn_offset_ms) DO NOTHING
`

type InsertTurnParams struct {
	DongleID         string             `json:"dongleId"`
	Route            string             `json:"route"`
	TurnTs           pgtype.Timestamptz `json:"turnTs"`
	TurnOffsetMs     int32              `json:"turnOffsetMs"`
	BearingBeforeDeg float32            `json:"bearingBeforeDeg"`
	BearingAfterDeg  float32            `json:"bearingAfterDeg"`
	DeltaDeg         float32            `json:"deltaDeg"`
	GpsLat           pgtype.Float8      `json:"gpsLat"`
	GpsLng           pgtype.Float8      `json:"gpsLng"`
}

func (q *Queries) InsertTurn(ctx context.Context, arg InsertTurnParams) error {
	_, err := q.db.Exec(ctx, insertTurn,
		arg.DongleID,
		arg.Route,
		arg.TurnTs,
		arg.TurnOffsetMs,
		arg.BearingBeforeDeg,
		arg.BearingAfterDeg,
		arg.DeltaDeg,
		arg.GpsLat,
		arg.GpsLng,
	)
	return err
}

const listTurnsForRoute = `-- name: ListTurnsForRoute :many
SELECT id, dongle_id, route, turn_ts, turn_offset_ms,
       bearing_before_deg, bearing_after_deg, delta_deg,
       gps_lat, gps_lng
FROM route_turns
WHERE dongle_id = $1 AND route = $2
ORDER BY turn_offset_ms ASC, id ASC
`

type ListTurnsForRouteParams struct {
	DongleID string `json:"dongleId"`
	Route    string `json:"route"`
}

func (q *Queries) ListTurnsForRoute(ctx context.Context, arg ListTurnsForRouteParams) ([]RouteTurn, error) {
	rows, err := q.db.Query(ctx, listTurnsForRoute, arg.DongleID, arg.Route)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouteTurn
	for rows.Next() {
		var i RouteTurn
		if err := rows.Scan(
			&i.ID,
			&i.DongleID,
			&i.Route,
			&i.TurnTs,
			&i.TurnOffsetMs,
			&i.BearingBeforeDeg,
			&i.BearingAfterDeg,
			&i.DeltaDeg,
			&i.GpsLat,
			&i.GpsLng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
