// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: segments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO segments (route_id, segment_number)
VALUES ($1, $2)
RETURNING id, route_id, segment_number,
          rlog_uploaded, qlog_uploaded,
          fcamera_uploaded, ecamera_uploaded,
          dcamera_uploaded, qcamera_uploaded,
          created_at
`

type CreateSegmentParams struct {
	RouteID       int32 `json:"routeId"`
	SegmentNumber int32 `json:"segmentNumber"`
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, createSegment, arg.RouteID, arg.SegmentNumber)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.SegmentNumber,
		&i.RlogUploaded,
		&i.QlogUploaded,
		&i.FcameraUploaded,
		&i.EcameraUploaded,
		&i.DcameraUploaded,
		&i.QcameraUploaded,
		&i.CreatedAt,
	)
	return i, err
}

const getSegment = `-- name: GetSegment :one
SELECT id, route_id, segment_number,
       rlog_uploaded, qlog_uploaded,
       fcamera_uploaded, ecamera_uploaded,
       dcamera_uploaded, qcamera_uploaded,
       created_at
FROM segments
WHERE route_id = $1 AND segment_number = $2
`

type GetSegmentParams struct {
	RouteID       int32 `json:"routeId"`
	SegmentNumber int32 `json:"segmentNumber"`
}

func (q *Queries) GetSegment(ctx context.Context, arg GetSegmentParams) (Segment, error) {
	row := q.db.QueryRow(ctx, getSegment, arg.RouteID, arg.SegmentNumber)
	var i Segment
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.SegmentNumber,
		&i.RlogUploaded,
		&i.QlogUploaded,
		&i.FcameraUploaded,
		&i.EcameraUploaded,
		&i.DcameraUploaded,
		&i.QcameraUploaded,
		&i.CreatedAt,
	)
	return i, err
}

const listSegmentsByRoute = `-- name: ListSegmentsByRoute :many
SELECT id, route_id, segment_number,
       rlog_uploaded, qlog_uploaded,
       fcamera_uploaded, ecamera_uploaded,
       dcamera_uploaded, qcamera_uploaded,
       created_at
FROM segments
WHERE route_id = $1
ORDER BY segment_number ASC
`

func (q *Queries) ListSegmentsByRoute(ctx context.Context, routeID int32) ([]Segment, error) {
	rows, err := q.db.Query(ctx, listSegmentsByRoute, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.SegmentNumber,
			&i.RlogUploaded,
			&i.QlogUploaded,
			&i.FcameraUploaded,
			&i.EcameraUploaded,
			&i.DcameraUploaded,
			&i.QcameraUploaded,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSegmentUpload = `-- name: UpdateSegmentUpload :exec
UPDATE segments
SET rlog_uploaded = COALESCE($1, rlog_uploaded),
    qlog_uploaded = COALESCE($2, qlog_uploaded),
    fcamera_uploaded = COALESCE($3, fcamera_uploaded),
    ecamera_uploaded = COALESCE($4, ecamera_uploaded),
    dcamera_uploaded = COALESCE($5, dcamera_uploaded),
    qcamera_uploaded = COALESCE($6, qcamera_uploaded)
WHERE route_id = $7 AND segment_number = $8
`

type UpdateSegmentUploadParams struct {
	RlogUploaded    pgtype.Bool `json:"rlogUploaded"`
	QlogUploaded    pgtype.Bool `json:"qlogUploaded"`
	FcameraUploaded pgtype.Bool `json:"fcameraUploaded"`
	EcameraUploaded pgtype.Bool `json:"ecameraUploaded"`
	DcameraUploaded pgtype.Bool `json:"dcameraUploaded"`
	QcameraUploaded pgtype.Bool `json:"qcameraUploaded"`
	RouteID         int32       `json:"routeId"`
	SegmentNumber   int32       `json:"segmentNumber"`
}

func (q *Queries) UpdateSegmentUpload(ctx context.Context, arg UpdateSegmentUploadParams) error {
	_, err := q.db.Exec(ctx, updateSegmentUpload,
		arg.RlogUploaded,
		arg.QlogUploaded,
		arg.FcameraUploaded,
		arg.EcameraUploaded,
		arg.DcameraUploaded,
		arg.QcameraUploaded,
		arg.RouteID,
		arg.SegmentNumber,
	)
	return err
}
