// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, updated_at
FROM settings
WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i Setting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const insertSettingIfMissing = `-- name: InsertSettingIfMissing :exec
INSERT INTO settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
`

type InsertSettingIfMissingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) InsertSettingIfMissing(ctx context.Context, arg InsertSettingIfMissingParams) error {
	_, err := q.db.Exec(ctx, insertSettingIfMissing, arg.Key, arg.Value)
	return err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO settings (key, value)
VALUES ($1, $2)
ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = now()
RETURNING key, value, updated_at
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error) {
	row := q.db.QueryRow(ctx, upsertSetting, arg.Key, arg.Value)
	var i Setting
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}
