// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTripByRouteID = `-- name: GetTripByRouteID :one
SELECT id, route_id, distance_meters, duration_seconds, max_speed_mps,
       avg_speed_mps, engaged_seconds, start_address, end_address,
       start_lat, start_lng, end_lat, end_lng, computed_at
FROM trips
WHERE route_id = $1
`

func (q *Queries) GetTripByRouteID(ctx context.Context, routeID int32) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByRouteID, routeID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.DistanceMeters,
		&i.DurationSeconds,
		&i.MaxSpeedMps,
		&i.AvgSpeedMps,
		&i.EngagedSeconds,
		&i.StartAddress,
		&i.EndAddress,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.ComputedAt,
	)
	return i, err
}

const listTripsByDongleID = `-- name: ListTripsByDongleID :many
SELECT t.id, t.route_id, t.distance_meters, t.duration_seconds, t.max_speed_mps,
       t.avg_speed_mps, t.engaged_seconds, t.start_address, t.end_address,
       t.start_lat, t.start_lng, t.end_lat, t.end_lng, t.computed_at,
       r.dongle_id, r.route_name, r.start_time
FROM trips t
JOIN routes r ON r.id = t.route_id
WHERE r.dongle_id = $1
ORDER BY r.start_time DESC NULLS LAST, r.id DESC
LIMIT $2 OFFSET $3
`

type ListTripsByDongleIDParams struct {
	DongleID string `json:"dongleId"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListTripsByDongleIDRow struct {
	ID              int32              `json:"id"`
	RouteID         int32              `json:"routeId"`
	DistanceMeters  pgtype.Float8      `json:"distanceMeters"`
	DurationSeconds pgtype.Int4        `json:"durationSeconds"`
	MaxSpeedMps     pgtype.Float8      `json:"maxSpeedMps"`
	AvgSpeedMps     pgtype.Float8      `json:"avgSpeedMps"`
	EngagedSeconds  pgtype.Int4        `json:"engagedSeconds"`
	StartAddress    pgtype.Text        `json:"startAddress"`
	EndAddress      pgtype.Text        `json:"endAddress"`
	StartLat        pgtype.Float8      `json:"startLat"`
	StartLng        pgtype.Float8      `json:"startLng"`
	EndLat          pgtype.Float8      `json:"endLat"`
	EndLng          pgtype.Float8      `json:"endLng"`
	ComputedAt      pgtype.Timestamptz `json:"computedAt"`
	DongleID        string             `json:"dongleId"`
	RouteName       string             `json:"routeName"`
	StartTime       pgtype.Timestamptz `json:"startTime"`
}

func (q *Queries) ListTripsByDongleID(ctx context.Context, arg ListTripsByDongleIDParams) ([]ListTripsByDongleIDRow, error) {
	rows, err := q.db.Query(ctx, listTripsByDongleID, arg.DongleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripsByDongleIDRow
	for rows.Next() {
		var i ListTripsByDongleIDRow
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.DistanceMeters,
			&i.DurationSeconds,
			&i.MaxSpeedMps,
			&i.AvgSpeedMps,
			&i.EngagedSeconds,
			&i.StartAddress,
			&i.EndAddress,
			&i.StartLat,
			&i.StartLng,
			&i.EndLat,
			&i.EndLng,
			&i.ComputedAt,
			&i.DongleID,
			&i.RouteName,
			&i.StartTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTripStatsByDongleID = `-- name: SumTripStatsByDongleID :one
SELECT
    COALESCE(SUM(t.distance_meters), 0)::DOUBLE PRECISION AS total_distance,
    COALESCE(SUM(t.duration_seconds), 0)::BIGINT          AS total_duration,
    COALESCE(SUM(t.engaged_seconds), 0)::BIGINT           AS total_engaged,
    COUNT(*)::BIGINT                                      AS trip_count
FROM trips t
JOIN routes r ON r.id = t.route_id
WHERE r.dongle_id = $1
`

type SumTripStatsByDongleIDRow struct {
	TotalDistance float64 `json:"totalDistance"`
	TotalDuration int64   `json:"totalDuration"`
	TotalEngaged  int64   `json:"totalEngaged"`
	TripCount     int64   `json:"tripCount"`
}

func (q *Queries) SumTripStatsByDongleID(ctx context.Context, dongleID string) (SumTripStatsByDongleIDRow, error) {
	row := q.db.QueryRow(ctx, sumTripStatsByDongleID, dongleID)
	var i SumTripStatsByDongleIDRow
	err := row.Scan(
		&i.TotalDistance,
		&i.TotalDuration,
		&i.TotalEngaged,
		&i.TripCount,
	)
	return i, err
}

const upsertTrip = `-- name: UpsertTrip :one
INSERT INTO trips (
    route_id,
    distance_meters,
    duration_seconds,
    max_speed_mps,
    avg_speed_mps,
    engaged_seconds,
    start_address,
    end_address,
    start_lat,
    start_lng,
    end_lat,
    end_lng,
    computed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (route_id) DO UPDATE SET
    distance_meters  = EXCLUDED.distance_meters,
    duration_seconds = EXCLUDED.duration_seconds,
    max_speed_mps    = EXCLUDED.max_speed_mps,
    avg_speed_mps    = EXCLUDED.avg_speed_mps,
    engaged_seconds  = EXCLUDED.engaged_seconds,
    start_address    = EXCLUDED.start_address,
    end_address      = EXCLUDED.end_address,
    start_lat        = EXCLUDED.start_lat,
    start_lng        = EXCLUDED.start_lng,
    end_lat          = EXCLUDED.end_lat,
    end_lng          = EXCLUDED.end_lng,
    computed_at      = EXCLUDED.computed_at
RETURNING id, route_id, distance_meters, duration_seconds, max_speed_mps,
          avg_speed_mps, engaged_seconds, start_address, end_address,
          start_lat, start_lng, end_lat, end_lng, computed_at
`

type UpsertTripParams struct {
	RouteID         int32              `json:"routeId"`
	DistanceMeters  pgtype.Float8      `json:"distanceMeters"`
	DurationSeconds pgtype.Int4        `json:"durationSeconds"`
	MaxSpeedMps     pgtype.Float8      `json:"maxSpeedMps"`
	AvgSpeedMps     pgtype.Float8      `json:"avgSpeedMps"`
	EngagedSeconds  pgtype.Int4        `json:"engagedSeconds"`
	StartAddress    pgtype.Text        `json:"startAddress"`
	EndAddress      pgtype.Text        `json:"endAddress"`
	StartLat        pgtype.Float8      `json:"startLat"`
	StartLng        pgtype.Float8      `json:"startLng"`
	EndLat          pgtype.Float8      `json:"endLat"`
	EndLng          pgtype.Float8      `json:"endLng"`
	ComputedAt      pgtype.Timestamptz `json:"computedAt"`
}

func (q *Queries) UpsertTrip(ctx context.Context, arg UpsertTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, upsertTrip,
		arg.RouteID,
		arg.DistanceMeters,
		arg.DurationSeconds,
		arg.MaxSpeedMps,
		arg.AvgSpeedMps,
		arg.EngagedSeconds,
		arg.StartAddress,
		arg.EndAddress,
		arg.StartLat,
		arg.StartLng,
		arg.EndLat,
		arg.EndLng,
		arg.ComputedAt,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.DistanceMeters,
		&i.DurationSeconds,
		&i.MaxSpeedMps,
		&i.AvgSpeedMps,
		&i.EngagedSeconds,
		&i.StartAddress,
		&i.EndAddress,
		&i.StartLat,
		&i.StartLng,
		&i.EndLat,
		&i.EndLng,
		&i.ComputedAt,
	)
	return i, err
}
