// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ui_users.sql

package db

import (
	"context"
)

const getUIUserByID = `-- name: GetUIUserByID :one
SELECT id, username, password_hash, created_at
FROM ui_users
WHERE id = $1
`

func (q *Queries) GetUIUserByID(ctx context.Context, id int32) (UiUser, error) {
	row := q.db.QueryRow(ctx, getUIUserByID, id)
	var i UiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUIUserByUsername = `-- name: GetUIUserByUsername :one
SELECT id, username, password_hash, created_at
FROM ui_users
WHERE username = $1
`

func (q *Queries) GetUIUserByUsername(ctx context.Context, username string) (UiUser, error) {
	row := q.db.QueryRow(ctx, getUIUserByUsername, username)
	var i UiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUIUser = `-- name: UpsertUIUser :one
INSERT INTO ui_users (username, password_hash)
VALUES ($1, $2)
ON CONFLICT (username) DO UPDATE SET password_hash = EXCLUDED.password_hash
RETURNING id, username, password_hash, created_at
`

type UpsertUIUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) UpsertUIUser(ctx context.Context, arg UpsertUIUserParams) (UiUser, error) {
	row := q.db.QueryRow(ctx, upsertUIUser, arg.Username, arg.PasswordHash)
	var i UiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
